### ISSUE TITLE
Do I have to put the FASTQ in the MTBseq.pl folder?

### ISSUE THREAD

**Issue by tseemann** [ngs-fzb/MTBseq_source#12]
I am trying out MTBseq but am having some difficulties.

1. I have installed it in a folder `/opt/mtbseq/` as user `nobody` and have it in my `$PATH`
2. I put my reads in `/home/torst/tbdata` with the right naming system.
3. Then I `cd  /home/torst/tdbdata` and run `MTBseq.pl --step TBbwa` as user `torst`

But i get these errors:
```
<ERROR> [2018-06-24 18:19:47]   move failed: TBbwa.pm line: 116
```
Which i track backwards to the `.bamlog` to find:
```
/opt/mtbseq/var/ref/M._tuberculosis_H37Rv_2015-11-13.fasta.pac' : Permission denied
```

Do i really need write access to the software folder?
That can never work on a HPC system.

Could you make it such that you have an `--outdir` and/**or** copy the reference into that first, along with all the other folders?

**Comment by cutpatel** [comment]
No, fastq files can be located anywhere from where you can call the MTBseq.pl and outputfolders will be created at this location.
MTBseq is checking for several index files and will create them in the directory of the reference. This is usually done during the first run, but files are now already inlcuded from the start.

**Comment by tseemann** [comment]
It's good you are including them from the start, as once software is installed by an admin, we have no rights to write to that folder, so therefore can't use the inbuilt references without copying them elsewhere?

BUT

https://github.com/ngs-fzb/MTBseq_source/issues/14  is a problem!
