### ISSUE TITLE
Problems with GATK and provided reference

### ISSUE THREAD

**Issue by kristyhoran** [ngs-fzb/MTBseq_source#14]
Hi,
I am trying to use your pipeline, I have been able to install in and run the first TBbwa.

However, after ensuring that java8 was being used (not java9) the following error resulted at the GATK step

```
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A USER ERROR has occurred (version 3.8-0-ge9d806836): 
INFO  10:20:10,530 SAMDataSource$SAMReaders - Initializing SAMRecords in serial 
##### ERROR
##### ERROR This means that one or more arguments or inputs in your command are incorrect.
##### ERROR The error message below tells you what is the problem.
##### ERROR
##### ERROR If the problem is an invalid argument, please check the online documentation guide
##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
##### ERROR
##### ERROR Visit our website and forum for extensive documentation and answers to 
##### ERROR commonly asked questions https://software.broadinstitute.org/gatk
##### ERROR
##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
##### ERROR
##### ERROR MESSAGE: Bad input: We encountered a non-standard non-IUPAC base in the provided reference: '0'
##### ERROR ------------------------------------------------------------------------------------------
```
After some investigation, it appeared that there was an inappropriate line ending in the reference, which I fixed, but which meant that the I had to re-index the fast file (`samtools faidx path/to/provided/reference.fasta`)

The pipeline appears to run to completion now.
Cheers
Kristy

**Comment by cutpatel** [comment]
Hi, 
could you specify which inappropriate line ending you found? Which system are you using?

I tried to reproduce the error, but it is all working fine for me:
Dowloaded the single reference fasta from github, has `LF` ending and is working.
Cloned repository to Ubuntu 16 virtual machine, `LF` ending and is working.
Cloned to Windows10, `CRLF` ending, placed on shared network space as is, still working with Ubuntu.

If you delete the index file MTBseq will recreate it as long as you have writing permissions in the directory of the reference. Also true for the BWA index files.

**Comment by 000CU000** [comment]
Hi, 
could you specify which inappropriate line ending you found? Which system are you using?

I tried to reproduce the error, but it is all working fine for me:
Dowloaded the single reference fasta from github, has LF ending and is working.
Cloned repository to Ubuntu 16 virtual machine, LF ending and is working.
Cloned to Windows10, CRLF ending, placed on shared network space as is, still working with Ubuntu.

If you delete the index file MTBseq will recreate it as long as you have writing permissions in the directory of the reference. Also true for the BWA index files.

**Comment by pvanheus** [comment]
I also find a problem with the provided reference index (OpenJDK 1.8.0_121 on Ubuntu 16.04.04). As with @kristyhoran rebuilding the reference index solves this. The symptoms in my case are a bit different.

1) Running in multi-threaded mode (but somehow only when using > 7 threads) I encountered an error like @kristyhoran reported. I'll note that RealignTargetCreator has previously [reported](https://gatkforums.broadinstitute.org/gatk/discussion/4583/nondeterministic-output-from-realignertargetcreator-with-using-threads) issues with multithreading but I think those are not relevant here.

2) Running in single threaded mode the `mpileup` step fills up a log with the error message "[E::fai_retrieve] Failed to retrieve block: unexpected end of file".

The `M._tuberculosis_H37Rv_2015-11-13.fasta.fai` file from Github contains the line:

`M.tuberculosis_H37Rv	4411532	35	4411532	4411533`

The version I build with `samtools faidx` has:

`M.tuberculosis_H37Rv    4411532 34      4411532 4411533`

which is consistent with the reference.

In any event, recreating the FASTA index solved the problem.

**Comment by tseemann** [comment]
The differences in the `.fai` file are due to the different line endings in Unices.
Windows/DOS uses CR+LF  (2 chars) whereas MacOS and Linux use just 1.
The 34 , 35 are how many chars per line to skip when looking up the reference.
If you index on one system, and use on a different one, you will get a TOTAL MESS.

**Comment by cutpatel** [comment]
Seems like the `.fasta` got `CRLF` during checkout to a shared network location and thereby got 35 in the `.fai` during indexing. Uploaded now a `.fai` from a `LF` EOL `.fasta`.

**Comment by Ahusnoo** [comment]
I was having a  similar issue. Regenerating the fasta.fai file using samtools faidx tool resolved it. Hope this helps someone who having similar issue in the future!
