### ISSUE TITLE
non-unique naming in /tmp

### ISSUE THREAD

**Issue by martinghunt** [ngs-fzb/MTBseq_source#22]
Files are written into `/tmp` that are not guaranteed to have a unique name. I have this error:

```
[E::hts_open_format] Failed to open file /tmp/sampleID_libID.sorted.0000.bam
samtools sort: failed to create temporary file "/tmp/sampleID_libID.sorted.0000.bam": File exists
```
 in the log file `Bam/sampleID_libID.bamlog`. I appreciate that the sample and library ID are put in the name, which is probably unique, but in my case it's not unique and breaks my pipeline if two runs happen to land on the same node of our compute cluster at the same time.

I suggest using [File::Temp](https://perldoc.perl.org/File/Temp.html) to safely create a temporary directory.

**Comment by TaKohl** [comment]
Hello, 

you are fully correct, we inherently assume the combination of sample ID and library ID to be unique. This is actually part of a feature of the pipeline, i.e. the semi-automated data processing. We could of course employ some workaround, but this will probably compromise ease of use, so we decided to stick with the requirement of unique IDs.

best wishes, 
Thomas
