### ISSUE TITLE
GATK error with test data

### ISSUE THREAD

**Issue by dankein** [ngs-fzb/MTBseq_source#23]
The pipeline is stopping at the  "Start GATK refinement" step.

I'm seeing the following error in the gatk.bamlog file:

ERROR StatusLogger Unable to create class org.apache.logging.log4j.core.impl.Log4jContextFactory specified in jar:file:/[conda env]/opt/gatk-3.8/GenomeAnalysisTK.jar!/META-INF/log4j-provider.properties
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...

I'm using Java 1.8

**Comment by cutpatel** [comment]
Not a problem with the test data, but a problem of the GATK program with your environment. Please see https://gatkforums.broadinstitute.org/gatk/discussion/10004/realignertargetcreator-hangs and try GATK 3.8.1. Just exchange the .jar file.

**Comment by dankein** [comment]
Thanks very much, everything is working well now. I wasn't sure if GATK 3.8.1 was supported or not.

**Comment by cutpatel** [comment]
Great!
