### ISSUE TITLE
GATK error failed 256

### ISSUE THREAD

**Issue by ChiehYin** [ngs-fzb/MTBseq_source#24]
I ran TBfull and it came out failed:256 message after GATK refinement started. 
Is there any file for searching failed code?

**Comment by cutpatel** [comment]
This has been clarified a long time ago by mail, just in case others run into the same issue.

For every analyzed file there are step specific log files. To trace the GATK error have look into the `GATK_Bam` directory and the respective sample `.gatk.bamlog` to find the GATK error message

**Comment by peflanag** [comment]
Hi, I am having the same issue and have gone in to look at the bamlog file. The only think is I don't know what to do when I see the error. I tried to go to the website it stated but it doesn't load. I have copied the bamlog and MTBseq --TBfull log below. 

Cheers,

Peter
[MTBseq_2019-09-09_linux-biostation.log](https://github.com/ngs-fzb/MTBseq_source/files/3591146/MTBseq_2019-09-09_linux-biostation.log)


The error seems to be with samtools and a high quality score of 65
[bamlog.txt](https://github.com/ngs-fzb/MTBseq_source/files/3591145/bamlog.txt)
