### ISSUE TITLE
compare isolates in different sequencing runs

### ISSUE THREAD

**Issue by alantsangmb** [ngs-fzb/MTBseq_source#28]
I have successfully run MTBseq on all the fastq files in a single sequencing run.
I am curious to know that if MTBseq could analyse the output files for different runs using TBjoin, TBamend and TBgroups, so that I could compare the isolates in different sequencing runs without re-mapping the fastq files again?

**Comment by cutpatel** [comment]
At the moment all files to be analyzed in the joined analysis need to be in the same folder and subfolders. You need the contents of `Called` and `Position_Tables`

```
TBjoin 
         Input files: 
 

- Called/[SampleID]_[LibID]_[*].gatk_position_variants_[mincovf]_[mincovr]_[minfreq]_[minphred20]_[all_vars][snp_vars][lowfreq_vars].tab

- Position_Tables/[SampleID]_[LibID]_[*].gatk_position_table.tab
```

You could think about a centralized analysis directory to which you copy all fastq files or if you want to keep them at their original location, to symlink them.

For now, if you already have sepearate MTBseq analysis "environments" you can decide to symlink the contents of the "Called" and "Position_Tables" into the "environment" of MTBseq where you want to perform the joint analysis.
