### ISSUE TITLE
No Read Files To Map

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#31]
Hi All,

I am trying to run MTBseq and get the following error:

"No read files to map"

Anyone have any ideas? I have attached a copy of the terminal window below.

Cheers,

Peter

(base) linux-biostation@Linux-BioStation:~$ MTBseq --step TBfull '/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/IEMDR03_S3_L001_R1_001.fastq.gz' + '/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/IEMDR03_S3_L001_R2_001.fastq.gz' 
Missing option after +
<INFO>	[2019-07-01 14:08:02]	Found perl module: MCE
<INFO>	[2019-07-01 14:08:02]	Found perl module: Statistics::Basic
<INFO>	[2019-07-01 14:08:02]	Found bwa in your PATH!
<INFO>	[2019-07-01 14:08:02]	Found samtools in your PATH!
<INFO>	[2019-07-01 14:08:02]	Found gatk3 in your PATH!
<INFO>	[2019-07-01 14:08:02]	Found picard in your PATH!

MTBseq 1.0.3 - Copyright (C) 2018   Thomas A. Kohl, Robin Koch, Christian Utpatel,
                              Maria Rosaria De Filippo, Viola Schleusener,
                              Patrick Beckert, Daniela M. Cirillo, Stefan Niemann

This program comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.

<INFO>	[2019-07-01 14:08:02]	You are linux-biostation.
<INFO>	[2019-07-01 14:08:02]	Your current working directory is: /home/linux-biostation
<INFO>	[2019-07-01 14:08:02]	You requested 1 thread(s) for the pipeline.

<INFO>	[2019-07-01 14:08:02]	Your parameter setting is:
<INFO>	[2019-07-01 14:08:02]	--step		TBfull
<INFO>	[2019-07-01 14:08:02]	--continue	0
<INFO>	[2019-07-01 14:08:02]	--samples	NONE
<INFO>	[2019-07-01 14:08:02]	--project	NONE
<INFO>	[2019-07-01 14:08:02]	--resilist	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/var/res/MTB_Resistance_Mediating.txt
<INFO>	[2019-07-01 14:08:02]	--intregions	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/var/res/MTB_Extended_Resistance_Mediating.txt
<INFO>	[2019-07-01 14:08:02]	--categories	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/var/cat/MTB_Gene_Categories.txt
<INFO>	[2019-07-01 14:08:02]	--basecalib	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/var/res/MTB_Base_Calibration_List.vcf
<INFO>	[2019-07-01 14:08:02]	--ref		M._tuberculosis_H37Rv_2015-11-13.fasta
<INFO>	[2019-07-01 14:08:02]	--minbqual	13
<INFO>	[2019-07-01 14:08:02]	--all_vars	0
<INFO>	[2019-07-01 14:08:02]	--snp_vars	0
<INFO>	[2019-07-01 14:08:02]	--lowfreq_vars	0
<INFO>	[2019-07-01 14:08:02]	--mincovf	4
<INFO>	[2019-07-01 14:08:02]	--mincovr	4
<INFO>	[2019-07-01 14:08:02]	--minphred20	4
<INFO>	[2019-07-01 14:08:02]	--minfreq	75
<INFO>	[2019-07-01 14:08:02]	--unambig	95
<INFO>	[2019-07-01 14:08:02]	--window	12
<INFO>	[2019-07-01 14:08:02]	--distance	12
<INFO>	[2019-07-01 14:08:02]	--quiet		0

<INFO>	[2019-07-01 14:08:02]	The following programs will be used, if necessary:
<INFO>	[2019-07-01 14:08:02]	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/opt/bwa_0.7.17
<INFO>	[2019-07-01 14:08:02]	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/opt/samtools_1.6
<INFO>	[2019-07-01 14:08:02]	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/opt/picard_2.17.0
<INFO>	[2019-07-01 14:08:02]	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/opt/GenomeAnalysisTK_3.8

<INFO>	[2019-07-01 14:08:02]	The following directories will be used, if necessary:
<INFO>	[2019-07-01 14:08:02]	/home/linux-biostation/Bam
<INFO>	[2019-07-01 14:08:02]	/home/linux-biostation/GATK_Bam
<INFO>	[2019-07-01 14:08:02]	/home/linux-biostation/Mpileup
<INFO>	[2019-07-01 14:08:02]	/home/linux-biostation/Position_Tables
<INFO>	[2019-07-01 14:08:02]	/home/linux-biostation/Called
<INFO>	[2019-07-01 14:08:02]	/home/linux-biostation/Joint
<INFO>	[2019-07-01 14:08:02]	/home/linux-biostation/Amend
<INFO>	[2019-07-01 14:08:02]	/home/linux-biostation/Classification
<INFO>	[2019-07-01 14:08:02]	/home/linux-biostation/Groups

<INFO>	[2019-07-01 14:08:02]	### [TBfull] selected ###

<ERROR>	[2019-07-01 14:08:02]	No read files to map! Check content of /home/linux-biostation!
(base) linux-biostation@Linux-BioStation:~$

**Comment by cutpatel** [comment]
You need to start mtbseq in the directory where your fastq files are. There are not yet options for defining input and output directories from the command line.

Navigate to /home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/

And start with MTBseq --step TBfull

**Comment by peflanag** [comment]
Oh I didn't realise that! I have tried that again but it still isn't working.



(base) linux-biostation@Linux-BioStation:~/Documents/Peter F Work/MTBseq Test/DK progression to MDR$ MTBseq --step TBfull
<INFO>	[2019-07-01 14:35:52]	Found perl module: MCE
<INFO>	[2019-07-01 14:35:52]	Found perl module: Statistics::Basic
<INFO>	[2019-07-01 14:35:52]	Found bwa in your PATH!
<INFO>	[2019-07-01 14:35:52]	Found samtools in your PATH!
<INFO>	[2019-07-01 14:35:52]	Found gatk3 in your PATH!
<INFO>	[2019-07-01 14:35:52]	Found picard in your PATH!
tee: Work/MTBseq: No such file or directory
tee: Test/DK: No such file or directory
tee: MDR/MTBseq_2019-07-01_linux-biostation.log: No such file or directory


MTBseq 1.0.3 - Copyright (C) 2018   Thomas A. Kohl, Robin Koch, Christian Utpatel,
                              Maria Rosaria De Filippo, Viola Schleusener,
                              Patrick Beckert, Daniela M. Cirillo, Stefan Niemann

This program comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.


<INFO>	[2019-07-01 14:35:53]	You are linux-biostation.
<INFO>	[2019-07-01 14:35:53]	Your current working directory is: /home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR
<INFO>	[2019-07-01 14:35:53]	You requested 1 thread(s) for the pipeline.

<INFO>	[2019-07-01 14:35:53]	Your parameter setting is:
<INFO>	[2019-07-01 14:35:53]	--step		TBfull
<INFO>	[2019-07-01 14:35:53]	--continue	0
<INFO>	[2019-07-01 14:35:53]	--samples	NONE
<INFO>	[2019-07-01 14:35:53]	--project	NONE
<INFO>	[2019-07-01 14:35:53]	--resilist	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/var/res/MTB_Resistance_Mediating.txt
<INFO>	[2019-07-01 14:35:53]	--intregions	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/var/res/MTB_Extended_Resistance_Mediating.txt
<INFO>	[2019-07-01 14:35:53]	--categories	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/var/cat/MTB_Gene_Categories.txt
<INFO>	[2019-07-01 14:35:53]	--basecalib	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/var/res/MTB_Base_Calibration_List.vcf
<INFO>	[2019-07-01 14:35:53]	--ref		M._tuberculosis_H37Rv_2015-11-13.fasta
<INFO>	[2019-07-01 14:35:53]	--minbqual	13
<INFO>	[2019-07-01 14:35:53]	--all_vars	0
<INFO>	[2019-07-01 14:35:53]	--snp_vars	0
<INFO>	[2019-07-01 14:35:53]	--lowfreq_vars	0
<INFO>	[2019-07-01 14:35:53]	--mincovf	4
<INFO>	[2019-07-01 14:35:53]	--mincovr	4
<INFO>	[2019-07-01 14:35:53]	--minphred20	4
<INFO>	[2019-07-01 14:35:53]	--minfreq	75
<INFO>	[2019-07-01 14:35:53]	--unambig	95
<INFO>	[2019-07-01 14:35:53]	--window	12
<INFO>	[2019-07-01 14:35:53]	--distance	12
<INFO>	[2019-07-01 14:35:53]	--quiet		0

<INFO>	[2019-07-01 14:35:53]	The following programs will be used, if necessary:
<INFO>	[2019-07-01 14:35:53]	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/opt/bwa_0.7.17
<INFO>	[2019-07-01 14:35:53]	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/opt/samtools_1.6
<INFO>	[2019-07-01 14:35:53]	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/opt/picard_2.17.0
<INFO>	[2019-07-01 14:35:53]	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/opt/GenomeAnalysisTK_3.8

<INFO>	[2019-07-01 14:35:53]	The following directories will be used, if necessary:
<INFO>	[2019-07-01 14:35:53]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/Bam
<INFO>	[2019-07-01 14:35:53]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/GATK_Bam
<INFO>	[2019-07-01 14:35:53]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/Mpileup
<INFO>	[2019-07-01 14:35:53]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/Position_Tables
<INFO>	[2019-07-01 14:35:53]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/Called
<INFO>	[2019-07-01 14:35:53]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/Joint
<INFO>	[2019-07-01 14:35:53]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/Amend
<INFO>	[2019-07-01 14:35:53]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/Classification
<INFO>	[2019-07-01 14:35:53]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/Groups

<INFO>	[2019-07-01 14:35:53]	### [TBfull] selected ###

<ERROR>	[2019-07-01 14:35:53]	No read files to map! Check content of /home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR!
(base) linux-biostation@Linux-BioStation:~/Documents/Peter F Work/MTBseq Test/DK progression to MDR$

**Comment by cutpatel** [comment]
Please read the requirements on the file name structure.

**Comment by peflanag** [comment]
I don't quite understand what it means by next generation sequencing library used. It was run on illumina. Do I rename to IEMDR03_Illumina_R1.fastq.gz


Cheers

**Comment by cutpatel** [comment]
You only need to remove the _001 from your  filename

**Comment by peflanag** [comment]
Cool. I've tried that but am getting an error in opening the Bam directory now. Sorry for the hassle!



(base) linux-biostation@Linux-BioStation:~/Documents/Peter F Work/MTBseq Test/DK progression to MDR$ MTBseq --step TBfull
<INFO>	[2019-07-01 15:08:39]	Found perl module: MCE
<INFO>	[2019-07-01 15:08:39]	Found perl module: Statistics::Basic
<INFO>	[2019-07-01 15:08:39]	Found bwa in your PATH!
<INFO>	[2019-07-01 15:08:39]	Found samtools in your PATH!
<INFO>	[2019-07-01 15:08:39]	Found gatk3 in your PATH!
<INFO>	[2019-07-01 15:08:39]	Found picard in your PATH!
tee: Work/MTBseq: No such file or directory
tee: Test/DK: No such file or directory
tee: MDR/MTBseq_2019-07-01_linux-biostation.log: No such file or directory


MTBseq 1.0.3 - Copyright (C) 2018   Thomas A. Kohl, Robin Koch, Christian Utpatel,
                              Maria Rosaria De Filippo, Viola Schleusener,
                              Patrick Beckert, Daniela M. Cirillo, Stefan Niemann

This program comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.


<INFO>	[2019-07-01 15:08:40]	You are linux-biostation.
<INFO>	[2019-07-01 15:08:40]	Your current working directory is: /home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR
<INFO>	[2019-07-01 15:08:40]	You requested 1 thread(s) for the pipeline.

<INFO>	[2019-07-01 15:08:40]	Your parameter setting is:
<INFO>	[2019-07-01 15:08:40]	--step		TBfull
<INFO>	[2019-07-01 15:08:40]	--continue	0
<INFO>	[2019-07-01 15:08:40]	--samples	NONE
<INFO>	[2019-07-01 15:08:40]	--project	NONE
<INFO>	[2019-07-01 15:08:40]	--resilist	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/var/res/MTB_Resistance_Mediating.txt
<INFO>	[2019-07-01 15:08:40]	--intregions	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/var/res/MTB_Extended_Resistance_Mediating.txt
<INFO>	[2019-07-01 15:08:40]	--categories	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/var/cat/MTB_Gene_Categories.txt
<INFO>	[2019-07-01 15:08:40]	--basecalib	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/var/res/MTB_Base_Calibration_List.vcf
<INFO>	[2019-07-01 15:08:40]	--ref		M._tuberculosis_H37Rv_2015-11-13.fasta
<INFO>	[2019-07-01 15:08:40]	--minbqual	13
<INFO>	[2019-07-01 15:08:40]	--all_vars	0
<INFO>	[2019-07-01 15:08:40]	--snp_vars	0
<INFO>	[2019-07-01 15:08:40]	--lowfreq_vars	0
<INFO>	[2019-07-01 15:08:40]	--mincovf	4
<INFO>	[2019-07-01 15:08:40]	--mincovr	4
<INFO>	[2019-07-01 15:08:40]	--minphred20	4
<INFO>	[2019-07-01 15:08:40]	--minfreq	75
<INFO>	[2019-07-01 15:08:40]	--unambig	95
<INFO>	[2019-07-01 15:08:40]	--window	12
<INFO>	[2019-07-01 15:08:40]	--distance	12
<INFO>	[2019-07-01 15:08:40]	--quiet		0

<INFO>	[2019-07-01 15:08:40]	The following programs will be used, if necessary:
<INFO>	[2019-07-01 15:08:40]	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/opt/bwa_0.7.17
<INFO>	[2019-07-01 15:08:40]	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/opt/samtools_1.6
<INFO>	[2019-07-01 15:08:40]	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/opt/picard_2.17.0
<INFO>	[2019-07-01 15:08:40]	/home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/opt/GenomeAnalysisTK_3.8

<INFO>	[2019-07-01 15:08:40]	The following directories will be used, if necessary:
<INFO>	[2019-07-01 15:08:40]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/Bam
<INFO>	[2019-07-01 15:08:40]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/GATK_Bam
<INFO>	[2019-07-01 15:08:40]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/Mpileup
<INFO>	[2019-07-01 15:08:40]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/Position_Tables
<INFO>	[2019-07-01 15:08:40]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/Called
<INFO>	[2019-07-01 15:08:40]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/Joint
<INFO>	[2019-07-01 15:08:40]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/Amend
<INFO>	[2019-07-01 15:08:40]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/Classification
<INFO>	[2019-07-01 15:08:40]	/home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/Groups

<INFO>	[2019-07-01 15:08:40]	### [TBfull] selected ###
mkdir: cannot create directory ‘/home/linux-biostation/Documents/Peter’: File exists
mkdir: cannot create directory ‘F’: File exists
mkdir: cannot create directory ‘progression’: File exists
mkdir: cannot create directory ‘to’: File exists
mkdir: cannot create directory ‘/home/linux-biostation/Documents/Peter’: File exists
mkdir: cannot create directory ‘F’: File exists
mkdir: cannot create directory ‘progression’: File exists
mkdir: cannot create directory ‘to’: File exists
mkdir: cannot create directory ‘/home/linux-biostation/Documents/Peter’: File exists
mkdir: cannot create directory ‘F’: File exists
mkdir: cannot create directory ‘progression’: File exists
mkdir: cannot create directory ‘to’: File exists
mkdir: cannot create directory ‘/home/linux-biostation/Documents/Peter’: File exists
mkdir: cannot create directory ‘F’: File exists
mkdir: cannot create directory ‘progression’: File exists
mkdir: cannot create directory ‘to’: File exists
mkdir: cannot create directory ‘/home/linux-biostation/Documents/Peter’: File exists
mkdir: cannot create directory ‘F’: File exists
mkdir: cannot create directory ‘progression’: File exists
mkdir: cannot create directory ‘to’: File exists
mkdir: cannot create directory ‘/home/linux-biostation/Documents/Peter’: File exists
mkdir: cannot create directory ‘F’: File exists
mkdir: cannot create directory ‘progression’: File exists
mkdir: cannot create directory ‘to’: File exists
mkdir: cannot create directory ‘/home/linux-biostation/Documents/Peter’: File exists
mkdir: cannot create directory ‘F’: File exists
mkdir: cannot create directory ‘progression’: File exists
mkdir: cannot create directory ‘to’: File exists
mkdir: cannot create directory ‘/home/linux-biostation/Documents/Peter’: File exists
mkdir: cannot create directory ‘F’: File exists
mkdir: cannot create directory ‘progression’: File exists
mkdir: cannot create directory ‘to’: File exists
mkdir: cannot create directory ‘/home/linux-biostation/Documents/Peter’: File exists
mkdir: cannot create directory ‘F’: File exists
mkdir: cannot create directory ‘progression’: File exists
mkdir: cannot create directory ‘to’: File exists
mkdir: cannot create directory ‘/home/linux-biostation/Documents/Peter’: File exists
mkdir: cannot create directory ‘F’: File exists
mkdir: cannot create directory ‘progression’: File exists
mkdir: cannot create directory ‘to’: File exists
1 at /home/linux-biostation/miniconda3/bin/MTBseq line 373.
<ERROR>	[2019-07-01 15:08:40]	Can't open directory /home/linux-biostation/Documents/Peter F Work/MTBseq Test/DK progression to MDR/Bam: MTBseq.pl line: 373
(base) linux-biostation@Linux-BioStation:~/Documents/Peter F Work/MTBseq Test/DK progression to MDR$

**Comment by cutpatel** [comment]
Remove all spaces from your directory names or replace them by - or _.

**Comment by peflanag** [comment]
Amazing that seems to be running for me! Thank you so much!!

**Comment by cutpatel** [comment]
Great!

**Comment by peflanag** [comment]
So it stopped with another error. I'm guessing its a ram issue? The machine has 16GB of RAM though. I've pasted the end of the terminal below cause the full thing is quite long!


<INFO>	[2019-07-01 15:54:02]	Start creating position lists...
<INFO>	[2019-07-01 15:54:02]	Parsing reference genome M._tuberculosis_H37Rv_2015-11-13.fasta...
<INFO>	[2019-07-01 15:54:09]	Reference genome size (bp): 4411532!
<INFO>	[2019-07-01 15:54:09]	Start creating temporary output file...
<INFO>	[2019-07-01 15:54:09]	Finished creating temporary output file!
<INFO>	[2019-07-01 15:54:09]	Start parallel processing...
MCE::_dispatch_child: Failed to spawn worker 1: Cannot allocate memory at /home/linux-biostation/miniconda3/share/mtbseq-1.0.4-0/lib/TBtools.pm line 506.
(base) linux-biostation@Linux-BioStation:~/Documents/Peter_F_Work/MTBseq_Test/DK_progression_to_MDR$

**Comment by cutpatel** [comment]
16 GB should be very sufficent, at least for the first part oft the Pipeline.
Have not seen that error before.
Are you sure that you have access to all this memory?
You can try to restart the pipeline from the last successful step (--step TBlist --continue) and monitor the memory usage.
You can also try to limit the number of processes with --threads to a lower number than the default 8.

**Comment by peflanag** [comment]
Cool I'll try what you suggested. I also ran it on my college high compute clusters but it didn't seem to work. In the sense that it generated folders but in the folders there was nothing. Looking at the slurm.out file it finished with the error "failed: 256"

I have attached the file below if it helps.
[slurm-276008.txt](https://github.com/ngs-fzb/MTBseq_source/files/3353779/slurm-276008.txt)

**Comment by cutpatel** [comment]
There seems to be still a problem with your gatk. You should find results in the BAM folder and GATK BAM folder. For every step there are logfiles. There you can find the error of GATK.

**Comment by peflanag** [comment]
I'm not sure what it is I'm looking for in the log files in both those folders. However there is a lot of lines that say "inconsistent BAM file for pair 'xxxxxxxxx' continue anyway"

If it is a GATK issue I wonder is it because after i installed using the gatk3-register I never rename afterwards the /miniconda/bin/gatk3 to gatk like you had mentioned in your email before. The reason I didnt was cause when I did, MTBseq failed ant finding GATK. but when I changed back to GATK3 it found the dependency. I hope I am making sense. I've attached a screenshot showing the differenece


![Screenshot 2019-07-03 at 10 24 27](https://user-images.githubusercontent.com/32863969/60580334-d49bda00-9d7c-11e9-8753-249141f8a822.png)

**Comment by cutpatel** [comment]
home/users/flanagap/MTBseq_Test/GATK_Bam/IEMDR03_S3.gatk.bamlog

Look here please for the gatk error message.

The renaming is not needed anymore. Gatk3 is correct.

**Comment by peflanag** [comment]
So I found the error, its:

GATK jar file not found. Have you run "gatk3-register"?

I ran it again and got this:

It looks like GATK is already installed in your conda environment.
Run:
       gatk
    (or)
      GenomeAnalysisTK

**Comment by cutpatel** [comment]
I would once again recommend to start fresh. Something seems to be broken with the miniconda. It is really helpful to use separate environments for miniconda, see the link in our manual how to do this.

Then download exactly the GATK version from the link in the manual. Unpack it and run the register command on the .jar file.

**Comment by peflanag** [comment]
Cool will do! Cheers!

**Comment by peflanag** [comment]
Hey, so I removed conda and re added and added a separate environment in which to run MTBseq. It all seemed to work grand until it got to the last few lines in the screen shot I've added below. It says that a .bam doesnt exist and something else about line 83 in the TBstats.pm but there is nothing in the statistics folder. 

I looked in the gatk log and bam log files again for gatk errors but have found nothing. Could it be the sequence  files?

Sorry for all the questions! I've also attached the full log.
[MTBseq_2019-07-03_linux-biostation.log](https://github.com/ngs-fzb/MTBseq_source/files/3356359/MTBseq_2019-07-03_linux-biostation.log)


<img width="927" alt="Screenshot 2019-07-03 at 19 17 14" src="https://user-images.githubusercontent.com/32863969/60615824-f79fab80-9dc7-11e9-898c-441897fb3a40.png">

**Comment by cutpatel** [comment]
Great it worked so far. You should already habe now the variants in the called folder.

The error says it cannot find the BAM, but as it is there, as everything else now worked, the at that stage executed samtools flagstats command itself may have failed. I will need to look into this.
Can you please attach the mtbseq logfile from that execution

**Comment by peflanag** [comment]
Cool, the variants is in the called folder and I have attached the MTBseq log file below. 

Cheers for your help.


[MTBseq_2019-07-03_linux-biostation.log](https://github.com/ngs-fzb/MTBseq_source/files/3359393/MTBseq_2019-07-03_linux-biostation.log)

**Comment by peflanag** [comment]
Just to close this off,

I uninstalled all and created a new environment in miniconda3 that was solely for MTBseq. I reinstalled MTBseq and the dependancies and made a new directory with new fastq files and ran on the advice of 000CU000. All seemed to work fine!

Cheers for the help!
