### ISSUE TITLE
SNP trees

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#32]
Hi, 

This is more a query than an issue. After running

1) MTBseq --step TBfull
2) MTBseq --step TBjoin .......

I use the .....amended_u95_phylo_w12.plainIDs.fasta file to generate a newick file in FastTree

My query is, is this tree showing SNP differences in the distance between isolates? 

![Tree](https://user-images.githubusercontent.com/32863969/61947219-8f924e80-af9c-11e9-8090-d8be2e16f186.jpg)

**Comment by cutpatel** [comment]
No, as you most likely calculated a ml tree.
Try a minimum spanning or maximum parsimony tree.

**Comment by peflanag** [comment]
Cheers. Sorry if this sounds stupid, but can I still use the newick file to make a mini spanning or parsimony tree?

**Comment by cutpatel** [comment]
No you need the .fasta file alignment and another tool for that. Just google for it.

**Comment by peflanag** [comment]
Perfect cheers!
