### ISSUE TITLE
TBjoin issue

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#33]
Hi,

I tried running TBjoin and got an error. I have attached a screenshot below. Could you perhaps tell me what I did wrong?

Cheers,

Peter

![Screenshot 2019-08-27 at 11 11 16](https://user-images.githubusercontent.com/32863969/63762902-93770080-c8bb-11e9-8cb9-c019bdfa1439.png)

**Comment by cutpatel** [comment]
Difficult to say, have you looked in the directory if the file is really not there?

**Comment by peflanag** [comment]
I am away from that machine so I will have to look tomorrow. I know one of my students said they where going to try and run again so I will also touch base with them. I most also send on the logs from testing the line 83 in the TBstats.pm to you. I haven’t forgotten

**Comment by peflanag** [comment]
Many thanks for your help. I spoke with the student this morning and apparently its all running fine now. Thanks for the help. Apparently he just re-ran it again and it worked.
