### ISSUE TITLE
BWA Mapping Error

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#34]
Hi All,

I am trying to run MTBseq on all my sequence files and when it starts I get the error attached below. Can anyone shed light on this for me please?

Thanks,

P

![Screenshot 2019-09-04 at 12 33 07](https://user-images.githubusercontent.com/32863969/64251374-568cb880-cf10-11e9-9d33-49a32b1165e8.png)

**Comment by peflanag** [comment]
This is a copy of the line from the script in that location.


![Screenshot 2019-09-04 at 12 36 16](https://user-images.githubusercontent.com/32863969/64251525-a9ff0680-cf10-11e9-9a1e-fd08976d410f.png)

**Comment by cutpatel** [comment]
It tells you that your file names are wrong. Have look at the manual on the naming conventions. Fastq files need to end with r1.fastg.gz or r2.fastq.gz. fq instead of fastq is also accepted.

**Comment by peflanag** [comment]
Oh ok, I thought I had them all names correctly but must have missed one or two. Apologies for all the questions!
