### ISSUE TITLE
GATK error failed 256 - reopened

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#35]
Hi,
I am having the same issue as shown here and didnt know how to reopen.

https://github.com/ngs-fzb/MTBseq_source/issues/24

I have gone in to look at the bamlog file. The only think is I don't know what to do when I see the error. I tried to go to the website it stated but it doesn't load. I have copied the bamlog and MTBseq --TBfull log below. 

Cheers,

Peter
[MTBseq_2019-09-09_linux-biostation.log](https://github.com/ngs-fzb/MTBseq_source/files/3591146/MTBseq_2019-09-09_linux-biostation.log)

The error seems to be with samtools and a high quality score of 65
[bamlog.txt](https://github.com/ngs-fzb/MTBseq_source/files/3591145/bamlog.txt)

_Originally posted by @peflanag in https://github.com/ngs-fzb/MTBseq_source/issues/24#issuecomment-529516773_

**Comment by peflanag** [comment]
Hi Guys,

I have uninstalled and reinstalled MTBseq on a college cluster and when i run --check everything is fine. When I run my samples all works well until I get to the gatk refinement and then it fails with error 256. I don't understand why. Any ideas? I have attached a screenshot of the error and the full log from my run on the cluster. The bam.log says it cant find the gatk.jar file but --check says its there! 

Cheers,

Peter

<img width="1680" alt="Screenshot 2019-10-30 at 14 21 25" src="https://user-images.githubusercontent.com/32863969/67866673-3993f080-fb21-11e9-9022-c5f1f58d1f7f.png">

[MTBseq_2019-10-30_flanagap.log](https://github.com/ngs-fzb/MTBseq_source/files/3789429/MTBseq_2019-10-30_flanagap.log)

[slurm-280688 copy.txt](https://github.com/ngs-fzb/MTBseq_source/files/3789434/slurm-280688.copy.txt)

**Comment by ChiehYin** [comment]
Hi, 
Did you solve the problem? 
I also encountered the same issues. I ran on multiple samples and all of them completed suscessfully except two samples which stopped with the error message (error 256).

**Comment by peflanag** [comment]
hi @ChiehYin a user messaged me the following which I am about to try:

Hi,

I had the same issue while installing roary using conda. The solution that worked out for me was using mamba to install roary instead of conda. Mamba is a drop-in replacement for conda, offering higher speed and more reliable environment solutions.

If you don't have mamba in your base conda enviroment, just install it in base conda environment using

conda install -c conda-forge mamba

Then after installing mamba, activate your roary environment again. Then type the below commands to install it using mamba:

conda config --add channels r
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda
mamba install roary

Using the above approach, I was able to install roary in one go

**Comment by peflanag** [comment]
Hey @ChiehYin I can confirm that it worked!

**Comment by RichardUABC** [comment]
Hi,I  have the same error "failed 256", but muy ouputs  .bamlog are like this:

<INFO>  [2022-06-02 01:08:00]   bwa mem -t 4 -R '@RG\tID:ERR2512461_S12\tSM:ERR2512461\tPL:Illumina\tLB:S12' /opt/conda/share/mtbseq-1.0.4-2/var/ref/M._tuberculosis_H37Rv_2015-11-13.fasta  /home/ubuntudocker/MTB-AMR-CNN_MTBseq/ERR2512461_S12_R1.fastq.gz /home/ubuntudocker/MTB-AMR-CNN_MTBseq/ERR2512461_S12_R2.fastq.gz > /home/ubuntudocker/MTB-AMR-CNN_MTBseq/Bam/ERR2512461_S12.sam 2>> /home/ubuntudocker/MTB-AMR-CNN_MTBseq/Bam/ERR2512461_S12.bamlog
bwa mem -t 4 -R '@RG\tID:ERR2512461_S12\tSM:ERR2512461\tPL:Illumina\tLB:S12' /opt/conda/share/mtbseq-1.0.4-2/var/ref/M._tuberculosis_H37Rv_2015-11-13.fasta  /home/ubuntudocker/MTB-AMR-CNN_MTBseq/ERR2512461_S12_R1.fastq.gz /home/ubuntudocker/MTB-AMR-CNN_MTBseq/ERR2512461_S12_R2.fastq.gz > /home/ubuntudocker/MTB-AMR-CNN_MTBseq/Bam/ERR2512461_S12.sam 2>> /home/ubuntudocker/MTB-AMR-CNN_MTBseq/Bam/ERR2512461_S12.bamlog failed: 256
______________________________________________
 in the bamlog:

[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 264902 sequences (40000202 bp)...
[gzread] <fd:4>: too many length or distance symbols

or 

[M::bwa_idx_load_from_disk] read 0 ALT contigs
[W::bseq_read] the 2nd file has fewer sequences.
[M::process] read 4 sequences (9074220 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[mem_sam_pe] paired reads have different names: "†ù„„€€€……•š™›…”š—šŸ™š›šž›˜˜šŸŸž‰œœœ™ŸšœœŸžœœœ™˜š‰šŸ™š›”˜šž’‘Až’““’•Š–žš€”v’I›•›‘š™”’™šŠ˜Ÿ”ššššŸ˜™š–™ž™’3˜œ”‘œšž–ž›šžŸ—Šžž™š‹y”š›”•„™š—…›”6š–—••š••“””•–Ž•€––„–†{„;–‡•’•Š•––i‚•–…2–†Š…g3Œ5•—–;•—•”•…dyƒ5…0•––1j‘ej0~fh–4q`8f`:f;f†j9;", "‚<BB€š•‚š—•—@‚š”–’ƒ””:;•D›‚x‘šŠŠ‘Š™›•“˜‹’{’šš•“–’š—8z“y“‘œ–‡žšz™…;’™™…ŸŸž”š˜‰š”•–ˆw‡”žž›–˜žŸ™˜ššš‰š“y‰šf7š’g7Šxš™~Š7€1–‡‡‰”™š”h?–˜}Š‚avi0z…0v|†•—„x•…}~1’0t0ha11`ba”…}}~…~p|~29•ƒbb;3‡9„3…—–•31hzd9;|ba19j1}231a3a029293xi€}8a2b1"

or 

[M::bwa_idx_load_from_disk] read 0 ALT contigs
[W::bseq_read] the 2nd file has fewer sequences.
[M::process] read 12 sequences (75596 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[mem_sam_pe] paired reads have different names: "ERR2512437.1", "rkÔQ!&eW…ÞŽn“ý[™…“¨»”³ËÉ[Ñ{h‹Š/NãÉY-FÅmPóàG­%¬^‡4¬¬0ÄH_ôqRB ÊR<á*"

[mem_sam_pe] paired reads have different names: "ERR2512437.4", "ªè‡‚ô,£aEêµñ{oŸ^†Eeªæ­Žz.À¤³Ù‹S×…anš³b~fÕÙM!§œŸ.Œ‘ìþ3žüÃo†§ýÁª¦‰®šý¼,èó€*2²š"


II tried with the mamba solution and there is no difference. These sequences are downloaded from GenBank. what do you think is the problem?
