### ISSUE TITLE
MTBseq Failed at GATK refinment

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#36]
Hi,

I installed MTBseq on my college GPU cluster computer in a conda environment. However it failed at the GATK refinment step. I have attached a screenshot and logs below. Any help would be great. GATK is in my path so I dont know what it is!

Cheers,

Peter

<img width="1182" alt="Screenshot 2019-10-01 at 12 52 15" src="https://user-images.githubusercontent.com/32863969/65959591-51a52100-e44a-11e9-8e45-27c06c865099.png">

[MTBseq_2019-10-01_flanagap.log](https://github.com/ngs-fzb/MTBseq_source/files/3676035/MTBseq_2019-10-01_flanagap.log)

[IMRLH28_S15.gatk copy.txt](https://github.com/ngs-fzb/MTBseq_source/files/3676038/IMRLH28_S15.gatk.copy.txt)

**Comment by cutpatel** [comment]
"GATK jar file not found. Have you run "gatk3-register"?"

Thats the last entry in the log file, so apparently something is wrong with the gatk installation.

**Comment by peflanag** [comment]
I will try that and see

**Comment by peflanag** [comment]
Ok, I got it working! Totally my problem. I work between to clusters, one GPU and one non GPU and hadn't had the  gatk3-register set up in the env I was in!

Cheers for your help!
