### ISSUE TITLE
MTBseq in Parallel

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#37]
Hi,

I run MTBseq on a college cluster. I am just wondering can I run it in parallel across multiple nodes?

Cheers,

P

**Comment by Bowmore12** [comment]
Dear authors

I have same question.
As I have hundreds strains of fastq, I would like to speed up the analysis.

Best wishes
Yosmu

**Comment by TaKohl** [comment]
Hello, 

very good questions of course. Where the implemented tools offer that possibility, we use multi-threading. For that reason, you can specify the maximum number of threads as parameter. Sadly, there is no parallelization for much of the scripted functionality yet. What you can of course do would be to have multiple working directories and split up your input samples across them. You would later on have to copy the data into a unified directory of course if you want to perform joint comparisons. 

hope that helps, 
Thomas

**Comment by aspitaleri** [comment]
Hi Tomas,
yes indeed this what I am going to do using array feature in slurm. If I manage to do, I will put here the code of course. Actually I do have a bash pipeline for downstream analysis using slurm, so I will implement it.
Thanks!

**Comment by TaKohl** [comment]
Hello Andrea, 

that sounds very interesting, hope you succeed with this solution. Would be great to see your implementation.

best, 
thomas
