### ISSUE TITLE
Update Suggestions

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#38]
Hi,

I wonder could I make some suggestions for future updates of MTBseq?

1) I'm currently running it on a college cluster. Is it possible to run it in parallel across a number of nodes?

2) The file name system for accepting input files. Illumina ends in _R1_001 and its a bit a bit laborious having to clean up the naming system as well as make a samples text file when you've hundreds of samples. Unless theres a command line I'm not aware of?

3) The input/output directory. Can we point to a location? Its annoying that we can't and that everything is in the one directory that have to be moved after. Also, If I run TBfull on a run and a few weeks later run it again on a new run, if I want to run TBjoin on both I have to copy them into the one directory. It would be nicer to be able to point to the directory for the files.

4) Can it run on a GPU or on more threads? Currently I am running 108 samples on 8threads. I started this on the morning of the 23rd Oct and it is now lunch time on the 25th and it is still on the creating positions lists. I'm just curious if there is a way in which it can be sped up.

Cheers,

P

**Comment by TaKohl** [comment]
Very good points. We are actually looking to include parallelization into the next version. I fear that running on a GPU will not be feasible, but streamlining and calculation in parallel processes will likely be included. Being strict with file naming conventions and the directory is less user friendly, but does inherently circumvent a ton of possible errors. Not sure what would be the best way there. For re-naming several files at once, you can use the mmv (multi move) command. And you can create file lists easily by piping the output of ls to a text file. 

Most importantly, the source code is freely available and you can modify it to your heart's desire. :)

**Comment by peflanag** [comment]
Hey cheers! I’m not sure I’m tech savvy enough to play around with the source code! However I use a high compute cluster now rather than running locally on my iMac Pro so I can use something call taskfarm to run it over a number of nodes. 

How do you pipe the output of ls to a text file?! Never knew this was a thing!

**Comment by TaKohl** [comment]
Basically: 
ls >> filenames.txt
More refined: 
https://unix.stackexchange.com/questions/296247/when-i-redirect-the-output-of-ls-to-a-file-the-filename-is-included-in-that-fil/296249

**Comment by peflanag** [comment]
Thanks so much man, I appreciate it!
