### ISSUE TITLE
No Sequence in Amend - PlainIDs.fasta

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#43]
Hi All,

I have managed to run MTBseq on 5 MiniSeq runs and generated MLTs. However, two of the runs failed to generate sequence in the PlainIDs.fasta file and I don't know why. Both logs for TBfull and TBjoin show that it finished fine.

I have attached the logs below if someone could point me in the right direction as to why it failed?

Cheers.

[MTBseq_TBfull_Log.txt](https://github.com/ngs-fzb/MTBseq_source/files/3885651/MTBseq_TBfull_Log.txt)
[MTBseq_TBjoin_Log.txt](https://github.com/ngs-fzb/MTBseq_source/files/3885652/MTBseq_TBjoin_Log.txt)

**Comment by foamy1881** [comment]
I have the same issue where all my amend files is empty and my distance matrix file in TBgroup is all 0. Have you manage to solve the issue?

**Comment by cutpatel** [comment]
Is the fasta file the only empty one? Do you have a correct joint table, are the datasets you want to join of sufficent quality?
Have a look at the FAQ how bad data is influencing your results. Bad data needs to be filtered before proceeding to the joining step.

https://github.com/ngs-fzb/MTBseq_source/blob/master/MTBseq%20FAQ.v01.pdf

**Comment by peflanag** [comment]
Hi @cutpatel how are you? I am trying to run a large set of dat for TBjoin. It ran but the amend folder with the PlainIDs.fasta didn't produce the aligned sequences. It just has the sample names.

I looked at the manual and I am wondering is there a quick away to ascertain what sample is the outlier? The manual says a recommended 30X depth and 95% breath and that it can be found int he dataset overview file created by MTBseq. But I cannot seem to find this file? What older is it in or where is it located?

Cheers,

P

**Comment by TaKohl** [comment]
Hello Peter, 

please have a look at the statistics file that lists e.g. coverage breadth and mean coverage depth. You can of course define your own thresholds, but a good start would be 50x mean coverage depth and >95% unambiguous coverage breadth. 

best, 
Thomas

**Comment by yosmu** [comment]
Hello TakoHl

Where is "coverage breadth" ?
I could not find it on

**Comment by Bowmore12** [comment]
Hello TaKohl

Let me confirm one point. Where is "coverage breadth" ?
I could not find it on Mapping_and_Variant_Statistics.tab.

$ head -n 1 Mapping_and_Variant_Statistics.tab
Date	SampleID	LibraryID	FullID	Total Reads	Mapped Reads	% Mapped Reads	Genome Size	Genome GC	(Any) Total Bases	% (Any) Total Bases	(Any) GC-Content	(Any) Coverage mean	(Any) Coverage median	(Unambiguous) Total Bases	% (Unambiguous) Total Bases	(Unambiguous) GC-Content	(Unambiguous) Coverage mean	(Unambiguous) Coverage median	SNPs	Deletions	Insertions	Uncovered	Substitutions (Including Stop Codons)

Many thanks,
yosmu

**Comment by TaKohl** [comment]
Ah, sorry, I was using internal lingo there. You can find the coverage breadth for positions covered by any reads here: (Any) Total Bases % (Any) Total Bases, and for positions with sufficient sequence data quality to fulfill the thresholds for variant calling here: (Unambiguous) Total Bases % (Unambiguous) Total Bases.
