### ISSUE TITLE
Stop in TBjoin

### ISSUE THREAD

**Issue by acebollada** [ngs-fzb/MTBseq_source#45]
I am analyzing 5 paired-end samples and at the time of doing the TBJoin I get the following error. "Could not find files for SampleID_LibID! Did you run TBlist and TBvariants for SampleID_LibID?" 
My samples.txt file has two columns separated by tabs, the first row is "SampleID" and "LibID" and the next five rows the sample name and the library name. All samples have the same library name. The previous steps are ok. Attach log-file. Someone's had this issue
[MTBseq_2019-11-26_.log](https://github.com/ngs-fzb/MTBseq_source/files/3895568/MTBseq_2019-11-26_.log)

Thank you for your help

**Comment by foamy1881** [comment]
I'm having some issue with the generating the sample.txt file also. Do you have an example of your sample.txt files? It quite confusing for me.

**Comment by foamy1881** [comment]
Forget the above.. I manage to solve the sample.txt files issue. Make sure you have first row "SampleID" and second row "LibID", third row "#Pos" and then follow by subsequent role with "Type"
"Allele" "CovFor" "CovRev" "Qual20" "Freq" "Cov" and last row "Subst". You can find more information under Table 3 in MTBSeq Manual. Make sure you populate all of them in column with the same as in your first row for remaining of your samples. Then you can continue with the TBjoin command line.

**Comment by acebollada** [comment]
> Forget the above.. I manage to solve the sample.txt files issue. Make sure you have first row "SampleID" and second row "LibID", third row "#Pos" and then follow by subsequent role with "Type"
"Allele" "CovFor" "CovRev" "Qual20" "Freq" "Cov" and last row "Subst". You can find more information under Table 3 in MTBSeq Manual. Make sure you populate all of them in column with the same as in your first row for remaining of your samples. Then you can continue with the TBjoin command line.

Do you mean row or first column??

**Comment by cutpatel** [comment]
TBjoin needs to know which samples should be joined. These samples you specify via a file you give to MTBseq with --samples.

 `--samples This OPTION requires a user supplied file specifying a set of datasets (e.g. samples.txt) as VALUE. The file must be a two-column, tab-separated file. Column 1 has to be your [SampleID]. Column 2 has to be your [LibID]. TBjoin requires this OPTION to be set.`

The filename can be any name, but the structure needs to be as mentioned above.
2 columns seperated by a tab.
No headers or other signs.

Example:

General structur of the input fastqs:
[SampleID]_[LibID]_[*]_[Direction].f(ast)q.gz
File names:
H37Rv_library789_R1.fastq.gz + H37Rv_library789_R2.fastq.gz
sample.txt:
H37Rv library789

Table3 in the manual shows you how the output of the TBjoin command will look like. You do not need to create this file manually.

**Comment by acebollada** [comment]
Thank you very much! I could solve it and run tbjoin correctly!

**Comment by cutpatel** [comment]
Great!

**Comment by amolares** [comment]
[MTBseq_2023-07-28_usuario.log](https://github.com/ngs-fzb/MTBseq_source/files/12193657/MTBseq_2023-07-28_usuario.log)
[samples.txt](https://github.com/ngs-fzb/MTBseq_source/files/12193659/samples.txt)
Hi all!!
I have a similar problem when using TBjoin. The same message is showed "Could not find files for 357-17-BAAR_S1_L001!" when I created a samples.txt with 2 tab separated columns.
I'm a bit confused about what I do wrong.
Any suggestion is welcome.

**Comment by cutpatel** [comment]
Hi,

please have a look at the file name structure in the manual. "Fields" are seperated by a "_" and the first 2 "fields" are used as unique identifiers, so the correct samples files should look in your case like this:
357-17-BAAR	S1
50-22-BAAR	S1

**Comment by amolares** [comment]
Many thanks. It works!!
