### ISSUE TITLE
No data in TBamend and TBgroup? Please help

### ISSUE THREAD

**Issue by foamy1881** [ngs-fzb/MTBseq_source#46]
<INFO>	[2019-11-28 12:25:50]	Start creating joint variant table...
<INFO>	[2019-11-28 12:25:50]	Start parsing M._tuberculosis_H37Rv_2015-11-13.fasta...
<INFO>	[2019-11-28 12:25:50]	Finished parsing M._tuberculosis_H37Rv_2015-11-13.fasta!
<INFO>	[2019-11-28 12:25:59]	Start parsing M._tuberculosis_H37Rv_2015-11-13_genes.txt...
<INFO>	[2019-11-28 12:26:02]	Finished parsing M._tuberculosis_H37Rv_2015-11-13_genes.txt...
<INFO>	[2019-11-28 12:26:02]	Parsing variant files...
<INFO>	[2019-11-28 12:26:09]	Finished parsing variant files!
<INFO>	[2019-11-28 12:26:09]	Sart printing joint variant file scaffold...
<INFO>	[2019-11-28 12:26:09]	Finished printing joint variant file scaffold!
<INFO>	[2019-11-28 12:26:09]	Start parsing position lists, extend called variants and complete joint variant list...
<INFO>	[2019-11-29 01:28:07]	Finished parsing position lists, extend called variants and complete joint variant list!
<INFO>	[2019-11-29 01:28:09]	Start printing coverage breadth output...
<INFO>	[2019-11-29 01:29:00]	Finished printing coverage breadth output!
<INFO>	[2019-11-29 01:29:04]	Finished creating joint variant table!

<INFO>	[2019-11-29 01:29:06]	Amending joint variant table:
<INFO>	[2019-11-29 01:29:06]	MTBphylo_joint_cf4_cr4_fr75_ph4_samples457.tab

<INFO>	[2019-11-29 01:29:06]	Start amending joint variant table...
<INFO>	[2019-11-29 01:29:06]	Start parsing /home/yfong/miniconda3/envs/MTBseq/share/mtbseq-1.0.4-0/var/cat/MTB_Gene_Categories.txt..
<INFO>	[2019-11-29 01:29:06]	Finished parsing /home/yfong/miniconda3/envs/MTBseq/share/mtbseq-1.0.4-0/var/cat/MTB_Gene_Categories.txt!
<INFO>	[2019-11-29 01:29:06]	Start parsing /home/yfong/miniconda3/envs/MTBseq/share/mtbseq-1.0.4-0/var/res/MTB_Resistance_Mediating.txt and /home/yfong/miniconda3/envs/MTBseq/share/mtbseq-1.0.4-0/var/res/MTB_Extended_Resistance_Mediating.txt..
<INFO>	[2019-11-29 01:29:07]	Finished parsing /home/yfong/miniconda3/envs/MTBseq/share/mtbseq-1.0.4-0/var/res/MTB_Resistance_Mediating.txt and /home/yfong/miniconda3/envs/MTBseq/share/mtbseq-1.0.4-0/var/res/MTB_Extended_Resistance_Mediating.txt!
<INFO>	[2019-11-29 01:31:46]	Start creating MTBphylo_joint_cf4_cr4_fr75_ph4_samples457_amended_u95_phylo.tab with window length 12...
<INFO>	[2019-11-29 01:31:46]	Finished creating MTBphylo_joint_cf4_cr4_fr75_ph4_samples457_amended_u95_phylo.tab with window length 12!
<INFO>	[2019-11-29 01:31:46]	Finished amending joint variant table!

<INFO>	[2019-11-29 01:31:46]	Calling groups from:
<INFO>	[2019-11-29 01:31:46]	MTBphylo_joint_cf4_cr4_fr75_ph4_samples457_amended_u95_phylo_w12.tab

<INFO>	[2019-11-29 01:31:46]	Start group calling...
<INFO>	[2019-11-29 01:31:46]	Start parsing MTBphylo_joint_cf4_cr4_fr75_ph4_samples457_amended_u95_phylo_w12.tab...
<INFO>	[2019-11-29 01:31:46]	Finished parsing MTBphylo_joint_cf4_cr4_fr75_ph4_samples457_amended_u95_phylo_w12.tab!
<INFO>	[2019-11-29 01:31:46]	Start building distance matrix for MTBphylo_joint_cf4_cr4_fr75_ph4_samples457_amended_u95_phylo_w12.tab...
<INFO>	[2019-11-29 01:31:47]	Finished building distance matrix for MTBphylo_joint_cf4_cr4_fr75_ph4_samples457_amended_u95_phylo_w12.tab!
<INFO>	[2019-11-29 01:31:47]	Start calling groups for MTBphylo_joint_cf4_cr4_fr75_ph4_samples457_amended_u95_phylo_w12.tab...
<INFO>	[2019-11-29 02:14:09]	Finished calling groups for MTBphylo_joint_cf4_cr4_fr75_ph4_samples457_amended_u95_phylo_w12.tab!
<INFO>	[2019-11-29 02:14:09]	Finished group calling!

<INFO>	[2019-11-29 02:14:09]	### MTBseq finished!!! ###

It finished the analysis for TBjoin, and proceed towards amend and grouping for distance matrix and phylo but the result doesn't seem right where I do not have any fasta sequence at all and also all distance matrix is all 0. Maybe I have done something wrong? But I can't spot it myself with limited knowledge in bioinformatics. 

 I zipped all the attachment.  

[D.zip](https://github.com/ngs-fzb/MTBseq_source/files/3903047/D.zip)
Can anyone please advise? and help?

**Comment by cutpatel** [comment]
Is the joint file only an example or the real output? Only the first 4 datasets have data. 
I would suggest to start the joining again and check that you file with the samples to join is correct. Also 457 samples to join will require more memory. Maybe you did also run out of memory?

**Comment by foamy1881** [comment]
Hi.. I have attached the output from TBlist, TBvariants, TBstats, TBstrains and lastly the final TBjoin file. I have included the first sample data only apart from the full join files. As far I know they do have some variants being called and have information. I'm not sure why I still get information after grouping and amending them? Also the machine did not indicate any faulty memory and this is a VM  Ubuntu 18.04 build with 24GB ram. 

Sorry I cant attached it but you can download the files from my dropbox share link as below: 

https://www.dropbox.com/s/zgfvgljhe0h0y92/Troubleshoot.zip?dl=0

Do you have an email I can contact you? I need help to process this for full report to government agency and global health.

**Comment by cutpatel** [comment]
After having a look at your statistics table I can see that many of your samples have bad values for %mapped reads, mean coverage and the % of unambigous identified bases. You need to exclude these datasets from the further analysis or must get better data for them. Please read the FAQ how bad datasets are influencing your results:

https://github.com/ngs-fzb/MTBseq_source/blob/master/MTBseq%20FAQ.v01.pdf
