### ISSUE TITLE
mpileup to vcf

### ISSUE THREAD

**Issue by acebollada** [ngs-fzb/MTBseq_source#47]
Hi,
I'm newbie at bioinformatic and I have one question.Do you recommend me some tool that is suitable to convert mpileup  files that MTBseq generates to vcf files to visualize in IGV?? Or is it possible with MTBSeq generates the vcf files?
Thank you in advance

**Comment by aspitaleri** [comment]
Hi
I have used VarScan for this purpose:
`java -jar VarScan.v2.3.9.jar mpileup2snp file.mpileup --output-vcf 1 --min-var-freq 0.75 > file.varscan75.vcf`

HTH

**Comment by acebollada** [comment]
Thank you 
I'll test it

**Comment by cutpatel** [comment]
Unfortunately MTBseq is not giving you a vcf, this should definetly be changed in the future.
Please be aware that the suggested workaround is a different variant caller that may give you other variants than the MTBseq variant calling routine.
