### ISSUE TITLE
w12.PlainIDs.fasta Missing info

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#48]
Hi, 

When I run MTBseq on most of my sequence runs it seems to run fine. However I recently ran it on a years worth of sequencing and after the TBjoin step the w12.PlainIDs.fasta file is empty meaning I cannot process it in RAxML to generate a newick file for a MLT. I've attached the file as well as the log file but I dont see any error in it! its just odd that on some runs the w12.PlainIDs file sometimes doesnt have any sequence.

[IMRL_Clusters_2019_joint_cf4_cr4_fr75_ph4_samples175_amended_u95_phylo_w12.plainIDs.txt](https://github.com/ngs-fzb/MTBseq_source/files/3916350/IMRL_Clusters_2019_joint_cf4_cr4_fr75_ph4_samples175_amended_u95_phylo_w12.plainIDs.txt)

[MTBseq_TBjoin_Log.txt](https://github.com/ngs-fzb/MTBseq_source/files/3916342/MTBseq_TBjoin_Log.txt)

**Comment by cutpatel** [comment]
See issue #43.
