### ISSUE TITLE
TBtools.pm error?

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#50]
Hi, 

I was trying to run TBjoin on a large sample size and it appeared to run and finish. But when I looked at the w12.PlainID.fasta file there was nothing in it. When I looked at the log there was a stream of string like the below with the line number changing from 1 to 23861. I'm not sure what it means. I cant send the log.txt file because its over 24GB in size!

Any ideas?

Peter

Use of uninitialized value $freq1 in substitution (s///) at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1767, <IN> line 4.
Use of uninitialized value $type in string eq at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1769, <IN> line 4.
Use of uninitialized value $allel1 in string eq at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1769, <IN> line 4.
Use of uninitialized value $type in hash element at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1770, <IN> line 4.
Use of uninitialized value $allel1 in hash element at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1771, <IN> line 4.
Use of uninitialized value $covf in numeric ge (>=) at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1774, <IN> line 4.
Use of uninitialized value $allel1 in pattern match (m//) at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1780, <IN> line 4.
Use of uninitialized value $allel1 in pattern match (m//) at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1781, <IN> line 4.
Use of uninitialized value $type in pattern match (m//) at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1785, <IN> line 4.
Use of uninitialized value $type in pattern match (m//) at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1785, <IN> line 4.
Use of uninitialized value $type in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1789, <IN> line 4.
Use of uninitialized value $allel1 in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1789, <IN> line 4.
Use of uninitialized value $covf in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1789, <IN> line 4.
Use of uninitialized value $covr in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1789, <IN> line 4.
Use of uninitialized value $qual20 in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1789, <IN> line 4.
Use of uninitialized value $freq1 in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1789, <IN> line 4.
Use of uninitialized value $cov in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1789, <IN> line 4.
Use of uninitialized value $subs in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1789, <IN> line 4.
Use of uninitialized value $allel1 in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1790, <IN> line 4.
Use of uninitialized value $subs in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1791, <IN> line 4.

**Comment by peflanag** [comment]
So this is the TBtools.pm file from the location in the paths above. However I have no idea if the stuff in it is right or not.

[TBtools.pm.zip](https://github.com/ngs-fzb/MTBseq_source/files/4040970/TBtools.pm.zip)

**Comment by cutpatel** [comment]
The TBtools.pm is the toolbox of MTBseq and harbours functions to process your data, this is why you see a fail message from there. If you have not changed something in there manually, this file should be good.

I would say that your joint file is already incorrect. Did you have a look at it? Is there any data in there?

Please see the FAQ on the joining process for further information. You need to filter bad quality datasets and you need sufficent memory for the calculation. If you say large dataset, how many samples are this? If your computer runs out of memory this step will fail without further error message.

**Comment by peflanag** [comment]
Hi, so I am running on a cluster/number of nodes and the number of samples is approx 150 samples. I have never changed the TBtools.pm file.

I looked in the Joint folder and theres a joint file there but it just lists the sample names and nothing else. So even though TBfull ran fine you think I need to further filter my dataset?

**Comment by cutpatel** [comment]
The number of nodes is not important. Memory matters. Although 150 samples are not that much.
Of course you have to look at the results of tbfull. The pipeline will also run completely on bad data, like samples containing only partly tb. In the end your data cannot be sufficient to be analyzed further. Look at the statistics file and numbers like percentage reads map, mean coverage and unambiguous coverage. Have a look at the FAQ which explains how bad datasets will let fail subsequent analysis.

**Comment by peflanag** [comment]
Cool will do! Thanks!

**Comment by peflanag** [comment]
Hi, I wanted to reopen this because I am trying to run TBjoin on some 950 samples! I am doing this on a computer cluster (ICHEC.ie).

I have only included samples with greater than 20X coverage (which worked in smaller analysis) and samples with 80% or greater mapping. But it just seems to not work. The cluster has 1.5TB of ram so I don't imagine it being a memory issue and TBjoin has worked on smaller samples. Just wondering if you have any idea? Or is it possible to append the amend files from all runs into one file to make an MLT rather than running TBjoin on all samples?

Cheers!

The log file is too large to upload but it just contains strings of the following;



Use of uninitialized value $allel1 in string eq at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1769, <IN> line 45.
Use of uninitialized value $type in hash element at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1770, <IN> line 45.
Use of uninitialized value $allel1 in hash element at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1771, <IN> line 45.
Use of uninitialized value $covf in numeric ge (>=) at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1774, <IN> line 45.
Use of uninitialized value $allel1 in pattern match (m//) at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1780, <IN> line 45.
Use of uninitialized value $allel1 in pattern match (m//) at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1781, <IN> line 45.
Use of uninitialized value $type in pattern match (m//) at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1785, <IN> line 45.
Use of uninitialized value $type in pattern match (m//) at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1785, <IN> line 45.
Use of uninitialized value $type in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1789, <IN> line 45.
Use of uninitialized value $allel1 in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1789, <IN> line 45.
Use of uninitialized value $covf in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1789, <IN> line 45.
Use of uninitialized value $covr in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1789, <IN> line 45.
Use of uninitialized value $qual20 in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1789, <IN> line 45.
Use of uninitialized value $freq1 in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1789, <IN> line 45.
Use of uninitialized value $cov in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1789, <IN> line 45.
Use of uninitialized value $subs in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1789, <IN> line 45.
Use of uninitialized value $allel1 in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1790, <IN> line 45.
Use of uninitialized value $subs in concatenation (.) or string at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1791, <IN> line 45.
Use of uninitialized value $freq1 in substitution (s///) at /ichec/home/users/peflanag/.conda/envs/MTBseq/share/mtbseq-1.0.4-0/lib/TBtools.pm line 1767, <IN> line 45.

**Comment by TaKohl** [comment]
Hello Peter, this is most likely due to the joint analysis step crashing. Given enough RAM it should be possible to do a joint calculation of 950 samples, but the calculation will take some time. One explanation might be that the cluster had a lot of other jobs running and could not provide enough RAM to MTBseq. Sadly, due to the way the process works it is currently not possible to simply mash together individual joint comparison files. We are working on a solution to increase speed and calculation efficiency though.

**Comment by peflanag** [comment]
Hey TaKohl, cheers for that! I look forward to the update for the speed and calculation!
