### ISSUE TITLE
--resislist 

### ISSUE THREAD

**Issue by foamy1881** [ngs-fzb/MTBseq_source#51]
Hi sorry for the basic command questions. I completed the whole pipeline and I can't seem to find the conferring gene resistance prediction for first line/second line TB drugs? until i see the extra option --resislist? Now given i have completed the whole process how do I use this option without going back to restart the whole analysis again?

**Comment by cutpatel** [comment]
Hi,
there is no seperate file for the resistance predictions, it is already included in the called variant files as additional annotation.
The --resilist option allows you to give MTBseq your own list while running the pipeline. As default it is already comming with curated list. (/MTBseq_source/var/res/MTB_Resistance_Mediating.txt)
Own list need to have the same format, but you also jsut modify the default list with mutations of interest.

**Comment by foamy1881** [comment]
is there an easier way to summarize the drug resistance files like the TBstats statistic table? instead of going to each individual called variant files?

**Comment by TaKohl** [comment]
Sad to say, not yet. But this is of course a very useful feature, and if we manage to complete version 2 of the tool, we will likely include this. 

In the meantime, a useful shortcut is to import the variant tables into Excel and sort for the respective columns. Another option for a set of strains would be to perform a joint comparison, and import the amended joint table into Excel. Just be aware that you need to use the primary, unfiltered list.

**Comment by aspitaleri** [comment]
Hi @foamy1881 I have a perl script to deal with this, if I understood well. Basically it takes the Called/*variants.tab files to generate a sigle tab files as following:

> name_strain gene_1 gene_2 gene_3
> SW1 Ala234Val Arg32Phe
> SW2 Thr43 Val56Tyr

you can custom the gene analysis of course. The script works pretty well and of course it could contains bugs, but so far it is okay. If you want try it email me in private. 
Best
