### ISSUE TITLE
No Joint Variant File To Amend

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#53]
Hi,

I am pooling together all my 302 samples from multiple TBfull steps to carry out one TBjoin step and when I run it stops after 1min 40sec and the log states the following:

<INFO>	[2020-04-10 13:28:21]	IMRLH94_L001.gatk_position_variants_cf4_cr4_fr75_ph4_outmode000.tab
<INFO>	[2020-04-10 13:28:21]	IMRLH96_L001.gatk_position_variants_cf4_cr4_fr75_ph4_outmode000.tab
<INFO>	[2020-04-10 13:28:21]	IMRLH99_S1.gatk_position_variants_cf4_cr4_fr75_ph4_outmode000.tab

<INFO>	[2020-04-10 13:28:21]	Start creating joint variant table...
<INFO>	[2020-04-10 13:28:21]	Start parsing M._tuberculosis_H37Rv_2015-11-13.fasta...
<INFO>	[2020-04-10 13:28:21]	Finished parsing M._tuberculosis_H37Rv_2015-11-13.fasta!
<INFO>	[2020-04-10 13:28:30]	Start parsing M._tuberculosis_H37Rv_2015-11-13_genes.txt...
<INFO>	[2020-04-10 13:28:33]	Finished parsing M._tuberculosis_H37Rv_2015-11-13_genes.txt...
<INFO>	[2020-04-10 13:28:33]	Parsing variant files...
<INFO>	[2020-04-10 13:28:45]	Finished parsing variant files!
<INFO>	[2020-04-10 13:28:45]	Sart printing joint variant file scaffold...
<INFO>	[2020-04-10 13:28:45]	Finished printing joint variant file scaffold!
<INFO>	[2020-04-10 13:28:45]	Start parsing position lists, extend called variants and complete joint variant list...
<INFO>	[2020-04-10 13:28:45]	Finished parsing position lists, extend called variants and complete joint variant list!
<INFO>	[2020-04-10 13:28:47]	Start printing coverage breadth output...
<INFO>	[2020-04-10 13:29:32]	Finished printing coverage breadth output!
<INFO>	[2020-04-10 13:29:36]	Finished creating joint variant table!

<ERROR>	[2020-04-10 13:29:38]	No joint variant file All_No_C10_joint_cf4_cr4_fr75_ph4_samples302.tab to amend! Check content of /ichec/work/ndlif075c/Peter/Clusters_2019/All_Except_C10/Joint!

I'm at a bit of a loss. Any help would be great!

**Comment by cutpatel** [comment]
Have you pooled only the variant files or also the position files? Both are needed! At best really pool all folders of the seperate runs.
And it helps if you attach the full log file.

**Comment by peflanag** [comment]
Sorry I didn't realise that I didn't attach the log file. I have attached it below now. Basically I pooled all the folders from the individual runs and ran MTBSeq TBjoin on that.

[MTBseq_TBjoin_Log.txt](https://github.com/ngs-fzb/MTBseq_source/files/4580808/MTBseq_TBjoin_Log.txt)

**Comment by cutpatel** [comment]
There are 301 files found, are you sure about 302?
What is the content of the Joint/ Folder?

Here seems to be the problem:
<INFO>	[2020-04-10 13:28:45]	Start parsing position lists, extend called variants and complete joint variant list...
<INFO>	[2020-04-10 13:28:45]	Finished parsing position lists, extend called variants and complete joint variant list!

There is no time delay, but this step should take a while. For 302 samples it will really take some time, more than a day.
When finishing so fast it is skipping all datasets, because it cannot find the position file to the variant file.

**Comment by peflanag** [comment]
Oh ok. I didn’t notice that. I’ll shave a go and look through them all. Thanks for the help and spotting that

**Comment by sajidjan80** [comment]
@cutpatel  please help
I have successfully analyzed more than 200 samples from multiple TBfull steps,  each sample is located in its separate folder starting from 700 to 900. I am sorry but I can't write samples.txt file.  Some of  my files of sample 724 are
/724/Called/724_ERR3335724.gatk_position_variants_cf4_cr4_fr75_ph4_outmode000.tab
/724/Called/724_ERR3335724.gatk_position_uncovered_cf4_cr4_fr75_ph4_outmode000.tab
/724/Position_Tables/724_ERR3335724.gatk_position_table.tab

**Comment by sajidjan80** [comment]
> Sorry I didn't realise that I didn't attach the log file. I have attached it below now. Basically I pooled all the folders from the individual runs and ran MTBSeq TBjoin on that.
> 
> [MTBseq_TBjoin_Log.txt](https://github.com/ngs-fzb/MTBseq_source/files/4580808/MTBseq_TBjoin_Log.txt)

Dear Peflanag please help in TBjoin
I have successfully analyzed more than 200 samples from multiple TBfull steps, each sample is located in its separate folder starting from 700 to 900. I am sorry but I can't write samples.txt file for TBjoin. Some of my files of sample 724 are
/724/Called/724_ERR3335724.gatk_position_variants_cf4_cr4_fr75_ph4_outmode000.tab
/724/Called/724_ERR3335724.gatk_position_uncovered_cf4_cr4_fr75_ph4_outmode000.tab
/724/Position_Tables/724_ERR3335724.gatk_position_table.tab

**Comment by peflanag** [comment]
Hi @sajidjan80 

I'm not a bioinformatician and very much self thought in command line and a novice! I normally keep an excel file with my sample IDs for when I want to batch loads of samples. That way I never have to type them all out. I just auto-populate excel. my samples go by years and location and number. 

For example 21(year)IE(location)01 so its 21IE01, 21IE02 etc. an d I just use L001 as the other identifier. Therefore you can just auto-populate down a column in excel. Hopefully, this makes sense.


I normally analyse each sequencing run as I do it. Once done, I have a master folder that I copy the required files into for TBjoin to run so at the end of the year I can analysis all my yearly samples.

**Comment by sajidjan80** [comment]
Dear peflanag
Cheers for your prompt response, 
me too not a bioinformatician.. however I used MTBseq for TB analsysis and now unable to join them 
Please just guide me from scratches,  which files from MTBseq folders , should i copy in master folder.. i mean there are two file in 'Called folder" one in "Table position" folder  etc

**Comment by peflanag** [comment]
hey,

So the directory you run TBjoin from has to have the following folders in it

Amend
Called
Groups
Joint
Position_Tables
Samples.txt file


Only the called and position_table folder will have info in them from the TBfull step. Once you run TBjoin the rest of the folders will become populated.


Hope this helps

**Comment by cutpatel** [comment]
> 
> 
> @cutpatel please help
> I have successfully analyzed more than 200 samples from multiple TBfull steps, each sample is located in its separate folder starting from 700 to 900. I am sorry but I can't write samples.txt file. Some of my files of sample 724 are
> /724/Called/724_ERR3335724.gatk_position_variants_cf4_cr4_fr75_ph4_outmode000.tab
> /724/Called/724_ERR3335724.gatk_position_uncovered_cf4_cr4_fr75_ph4_outmode000.tab
> /724/Position_Tables/724_ERR3335724.gatk_position_table.tab

It looks like you have analyzed every sample seperately until now. Right? You have at the moment 200 folders named with the SampleID?
As peflanag suggested you need to have all analyzed files with the result folders in one directory. Like "MTBseq" as main folder which has all the subdirectories mentioned by peflanag. Of course you can also copy all other result folders there to have everything in one place. You need to place all the siingle results files from your seperate runs into the respective folders. Like all "variants" and "uncovered" files from all samples into the "MTBseq/Called" folder, if you take my suggested main folder name.

This is also how you can use MTBseq in the first place. Just put all fastq data you want to analyze in one directory and start MTBseq on them. You can also add later more fastq data and just start MTBseq again, it will know which files were already processed. By this you hhave all you data iin one place and can start a joint analysis on whatever subselection you make with the samples.txt file.
