### ISSUE TITLE
Annotation File - Other organisms

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#56]
Hi,

This isn't an issue but more help needed but cant find where to add the tag.

I want to add Staph aureus to the /MTBseq_source/var/ref path. I have added the fasta file and want to add the annotation now. The only thing is I'm not sure how to get the file identical to the H37Rv.txt file thats in the path all ready. I downloaded the file from NCBI as a GFF3 file but format is different to that used by MTBseq. 

Where would you recommend one downloads annotation files? Is there a universal standard? DO I have to make it myself? I have attached a zip of the file from NCBI.

Cheers,

P

[CP007659_1.gff3.zip](https://github.com/ngs-fzb/MTBseq_source/files/4923929/CP007659_1.gff3.zip)

**Comment by TaKohl** [comment]
Hello P, 

that's a really good point regarding the annotation file. Regretfully, the format used by MTBseq is not a universal standard. On the other hand, it is a simple text file. If you want to use the annotation, you would need to get the respective information and create an annotation file in the required format yourself. If the annotation is not necessary for your application, you can simply leave the file empty.

best wishes, 
Thomas

**Comment by peflanag** [comment]
Hi Thomas,

Cheers for the reply! Thats a shame its not a universal standard. Do you think future updates might incorporate this? I only ask because its quite a vast amount of information to go through on the GFF3 file to make a file similar to the MTBseq format and I'm not sure what information i am suppose to pull out of it when theres a lot of lines like this


ID=cds-WP_001670266.1;Parent=gene-ER16_RS01905;Dbxref=Genbank:WP_001670266.1;Name=WP_001670266.1;gbkey=CDS;inference=COORDINATES:   protein motif:HMM:NF020442.1;locus_tag=ER16_RS01905;product=FRG   domain-containing protein;protein_id=WP_001670266.1;transl_table=11
--

Anyway I might see can I export an annotation file from BioNumerics!

Cheers for the reply,

All the best,

P

**Comment by TaKohl** [comment]
Hi Peter, 

there are different ways to obtain annotation information, including in more easily accessible text format. If possible, we'll include a more widely used format as input for MTBseq with a future update.

best, 
Thomas
