### ISSUE TITLE
MTBseq considers R1 and R2 as two different isolates rather than considering it as double reads of a single isolates.what shall i do?any help? 

### ISSUE THREAD

**Issue by AmanuelZewdu** [ngs-fzb/MTBseq_source#59]

**Comment by AmanuelZewdu** [comment]
MTBseq considers R1 and R2 as two different isolates rather than considering it as double reads of a single isolates.what shall i do?any help?

**Comment by cutpatel** [comment]
MTBseq will recognize R1 and R2 if the rest of the file names are the same and are following the rules from the Overview section of the manual. https://github.com/ngs-fzb/MTBseq_source/blob/master/MANUAL.md

Have again a look at the structure of fastq names and compare if your filenames stick to the rules. If they are considered as 2 different isolates but run withoput problems in the pipeline I would expect differences in the filenames (other than R1/R2).
