### ISSUE TITLE
Amend multifasta with reference?

### ISSUE THREAD

**Issue by Viloleal** [ngs-fzb/MTBseq_source#60]
Dear MTBseq developers,

I am running MTBseq (TBfull) using an _M.bovis_ reference (AF2122/97) and I am interested in the output files from the Amend command. I imagine that the multifasta that is obtained as an output could be considered the "core snps"? If so, I have realised that I am missing the reference sequence in this multifasta for me to build a phylogeny. Is this normal behaviour or am I doing something wrong here?

Thank you very much for your help,

Kind regards

**Comment by cutpatel** [comment]
Great you managed to run MTBseq with the reference genome of your choice! Please see also #57.
You are right that the reference genome sequence is not included in the concatenated SNP alignment and that this is the intended result. Usually you also do not need this to build the phylogeny, as all data is analyzed in respect to your reference. Therefore in the SNP alignment also monomorphic sites could be present.
To more precisely root your phylogeny it is rather recommended to include an outgroup in the analysis.
I still do not see why you would want to inlcude the reference, but one way would be to generate an artificial fastq dataset with zero errors from the reference fasta (e.g. with DWGSIM) and analyze this dataset together with your samples of interest.

**Comment by Viloleal** [comment]
Hi!
Sorry for taking so long to reply... and thank you very much for answering my queries!

I did check #57 beforehand but I would rather use an _M. bovis_ genome as I am mostly interested in animal tuberculosis and not so much on human TB. Even if they are very similar genetically, I am concerned of small differences that could be missed.

The reason why I am interested in the reference is because I am evaluating several snp calling pipelines for MTBC/M. bovis and most of the variant calling pipelines follow (more or less) the same principle. As you say, it is better to include and outgroup and removing the reference from the analysis may be an easier option. 

thanks!
