### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment:

### ISSUE THREAD

**Issue by ryobon-dev** [ngs-fzb/MTBseq_source#61]
When start using GATK PrintReads for Test-20_MTBSeq_nextseq_151bp... a fatal error has been detected by the Java Runtime Environment. The messages are in below.

 A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000114ae66f7, pid=7410, tid=0x0000000000002503
#
# JRE version: OpenJDK Runtime Environment (8.0_152-b12) (build 1.8.0_152-release-1056-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.152-b12 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libgkl_compression3719787253608670960.dylib+0x76f7]  deflate_medium+0x867
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/tomotada/Desktop/iwamoto/MTB_test/hs_err_pid7410.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
gatk3 -T --analysis_type PrintReads --reference_sequence /Users/tomotada/miniconda3/envs/MTBseq/share/mtbseq-1.0.4-1/var/ref/M._tuberculosis_H37Rv_2015-11-13.fasta --input_file /Users/tomotada/Desktop/iwamoto/MTB_test/GATK_Bam/Test-20_MTBSeq_nextseq_151bp.realigned.bam --BQSR /Users/tomotada/Desktop/iwamoto/MTB_test/GATK_Bam/Test-20_MTBSeq_nextseq_151bp.gatk.grp --num_cpu_threads_per_data_thread 1 --out /Users/tomotada/Desktop/iwamoto/MTB_test/GATK_Bam/Test-20_MTBSeq_nextseq_151bp.gatk.bam  2>> /Users/tomotada/Desktop/iwamoto/MTB_test/GATK_Bam/Test-20_MTBSeq_nextseq_151bp.gatk.bamlog failed: 64000

[hs_err_pid7410.log](https://github.com/ngs-fzb/MTBseq_source/files/5897166/hs_err_pid7410.log)

**Comment by TaKohl** [comment]
Hello ryobon-dev, 

sorry to say, this seems to be a problem with the gatk tool called by the pipeline. It might be a good idea to contact your local support for the java implementation in your system. And maybe just do a test run with gatk on its own.

best,
Thomas

**Comment by ryobon-dev** [comment]
Thanks for your reply.

 

I will try to fix this problem.

 

Best regards,

 

Tomotada
