### ISSUE TITLE
samples.txt file

### ISSUE THREAD

**Issue by sajidjan80** [ngs-fzb/MTBseq_source#63]
@cutpatel please help in TBjoin
I have successfully analyzed more than 200 samples from multiple TBfull steps, each sample is located in its separate folder starting from 700 to 900. I am sorry but I can't write samples.txt file for TBjoin.  Some of my files of sample 724 are
/724/Called/724_ERR3335724.gatk_position_variants_cf4_cr4_fr75_ph4_outmode000.tab
/724/Called/724_ERR3335724.gatk_position_uncovered_cf4_cr4_fr75_ph4_outmode000.tab
/724/Position_Tables/724_ERR3335724.gatk_position_table.tab

**Comment by cutpatel** [comment]
See #53.
