### ISSUE TITLE
position_tables with slurm

### ISSUE THREAD

**Issue by aspitaleri** [ngs-fzb/MTBseq_source#64]
Hi there,
position tables (TBlist) is so far the most consuming time of the pipeline, mainly in case of several samples. One way to accelerate it is to make it embarrassingly parallel using for instance parallel or better slurm/srun array.
I am working on that outside of the pipeline but I am wondering whether you find already a clean solution on it. 
Best

**Comment by cutpatel** [comment]
Hey,
not fully sure what you mean. The process itself is running multithreaded with MCE on as many workers as you have specified threads in the MTBseq command.

**Comment by aspitaleri** [comment]
Hi,
yes I am using --threads 8 as indicated in the manual:

 --threads This OPTION is used in TBbwa, TBmerge, TBrefine, TBpile and TBlist. By default, the OPTION is set to 1. The OPTION sets the maximum number of CPUs to use within the pipeline. You can use more than one core in order to execute the pipeline faster. 8 is the current maximum.

What I meant is how to run TBlist in embarrassingly parallel per each mpileup file since the calculation is independent:
_i.e._ 
on one node with 32 cores -> run 32 parallel mpileup files at once.

This will speed up the TBlist step a lot!
Best

**Comment by TaKohl** [comment]
Hello Andrea, 

very good point. Sadly, at this point, there is no parallelization for most of the scripted functionality. What you could do as a solution is to have multiple working directories and instances of MTBseq running, and merge the resulting output after the analysis is finished.

Alternatively, you can of course dive into the fully open and available source code and implement a parallelization solution. If you are going in this direction, it would of course be great if you could share. 

best, 
Thomas
