### ISSUE TITLE
Candida parapsilosis analysis

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#65]
Hi @TaKohl I was wondering could I ask your advice in relation to issue #57 that I asked a while back. I wanted to the relationship between 7 parapsilosis sequences for a friend. Normally I would run Fastp then Snippy to get an alignment fasta and draw a tree from that using RAxML and look at SNP-Dists for the NxN matrix. But its a diploid organism so snippy doesn't seem to like that!

I decided to try MTBseq and stuck the reference file where it needed to be and a blank annotated file. I ran everything with no errors but was shocked to see that it was 0 SNPs among the isolates and one showing 1 SNP difference. Now, this might be correct which suggests possible host to host transmission. But I just wanted to check does MTBseq work ok on a diploid organism?

Cheers!

**Comment by TaKohl** [comment]
Hello, 

the short answer is, MTBseq is not built for diploid organisms and should not be used for them. With default settings, the tool will only report variants if they have an allele frequency of 75% or higher. The main reason to include allele frequency for a non-diploid organism is that there can be issues with sequencing and of course subpopulations within a bacterial culture. 

So, ideally, I would recommend to look for a tool that is built for diploid organisms. However, you could try the low frequency mode of MTBseq and set the allele frequency to a lower value, e.g. 40%. That should theoretically allow for the detection of variants in diploid organisms, but no guarantees. :)

best, 
Thomas

**Comment by peflanag** [comment]
Ah ok cool! I was trying a number of other tools unsuccessfully and thought id give MTBseq a go. Figured it would be too good to be true! Cheers for the quick reply though! I might give the low freq option a go!
