### ISSUE TITLE
Wrong option name --minphred in MANUAL.md

### ISSUE THREAD

**Issue by msmdev** [ngs-fzb/MTBseq_source#66]
Under [OPTIONS & VALUES] in MANUAL.md there is an option --minphred listed, which  should be correctly listed as --minphred20. This should be corrected.

**Comment by TaKohl** [comment]
While I appreciate the suggestion, the manual clearly describes what this option is used for, and I do not believe that the option name is wrong, or even misleading. The option could of course also be labelled --minphred20 or --minphred20allelecalls to be even more self-explanatory. In general, we tried to maximize user friendliness, that's the reason for using mostly longer and hopefully mostly self-explanatory option labels.
