### ISSUE TITLE
High confidence mutation

### ISSUE THREAD

**Issue by GuilhemRoyer** [ngs-fzb/MTBseq_source#67]
Hi,

Thank you for this highly comprehensive and easy-to-use tool! I was just wondering how you define "high confidence SNP"? Indeed, from the technical guide proposed by the WHO (https://apps.who.int/iris/handle/10665/274443), some mutations such a _rpoB_ Q432K for example are considered as high confidence mutation for rifampicine resistance. However from in your table MTB_Resistance_Mediating.txt it is not considered as high confidence SNP. What reference document did you use?

And another question : are premature codon stop (in katG for example) taken into account?

Thanks!

Guilhem

**Comment by TaKohl** [comment]
Hello Guilhem, thanks very much for your interest in the pipeline. As detailed in the MTBseq publication, it is important to note that the default list used to annotate resistance-associated mutations is only a snapshot of the information we compiled from various data available to us at that time point. There has been a lot of new data reported in the last years, and the default list of MTBseq will lack some of the newly reported findings. You can easily modify the default list of MTBseq to include new information or tweak existing entries. To my knowledge, there are currently initiatives to publish a comprehensive list, and of course it would be a good idea to use that data to update the list used by MTBseq.
