### ISSUE TITLE
gatk.bamlog failed:256 when tested my own reference fasta

### ISSUE THREAD

**Issue by ryobon-dev** [ngs-fzb/MTBseq_source#68]
When I change the reference to my own created and set option --ref for TBfull, the gatk.bamlog failed:256 was shown. The below is the part of the log. Could you please advise me how to resolve this issue ?

[MTBseq_2021-07-25_tomotada.log](https://github.com/ngs-fzb/MTBseq_source/files/6873467/MTBseq_2021-07-25_tomotada.log)
[MTBseq_2021-07-25_tomotada.log](https://github.com/ngs-fzb/MTBseq_source/files/6873469/MTBseq_2021-07-25_tomotada.log)
gatk3 --analysis_type RealignerTargetCreator --reference_sequence /home/tomotada/miniconda3/share/mtbseq-1.0.4-0/var/ref/IMC_NC_000962_H37Rv.fasta --input_file /mnt/c/users/tomotada/Desktop/MTB_test/Bam/Test-20_MTBSeq_nextseq_151bp.bam --downsample_to_coverage 10000 --num_threads 1 --out /mnt/c/users/tomotada/Desktop/MTB_test/GATK_Bam/Test-20_MTBSeq_nextseq_151bp.gatk.intervals 2>> /mnt/c/users/tomotada/Desktop/MTB_test/GATK_Bam/Test-20_MTBSeq_nextseq_151bp.gatk.bamlog failed: 256

**Comment by TaKohl** [comment]
Sorry to hear that you have had problems with the pipeline. There are of course several issues to consider. It seems that the pipeline worked without problem before you changed the reference, is that correct? Likewise, have you only tested this specific dataset with the new reference genome? And does the calculation for this dataset work with the default reference genome?

**Comment by ryobon-dev** [comment]
Thank you for your response.
Yes, this dataset with default reference worked without problem. I had tested only this specific dataset with the new reference genome.

**Comment by cutpatel** [comment]
Have a look in the specific log file to see the error:
/mnt/c/users/tomotada/Desktop/MTB_test/GATK_Bam/Test-20_MTBSeq_nextseq_151bp.gatk.bamlog

**Comment by ryobon-dev** [comment]
Thanks,
When I check the same run with different PC, the problem was resolved.
