### ISSUE TITLE
How can I get a strain specific SNP from TBamed file ?

### ISSUE THREAD

**Issue by ryobon-dev** [ngs-fzb/MTBseq_source#71]
MTBseq is a great pipeline ! I performed comparison of 7 strains those from the outbreak. From the multi-fasta file I could extract six SNVs among these seven strains. However, I could not find where these 6 SNVs are located in the tab file by TBamend.

Could you please let me know how I can get a detailed information of the strain specific SNVs from the TB amend file ?

For your information, I have enclosed tab file and fasta file those I obtained by MTBseq-TBamend.

[TBamend_result.xlsx](https://github.com/ngs-fzb/MTBseq_source/files/7667334/TBamend_result.xlsx)
[NONE_joint_cf4_cr4_fr75_ph4_samples7_amended_u95_phylo_w12.plainIDs.txt](https://github.com/ngs-fzb/MTBseq_source/files/7667360/NONE_joint_cf4_cr4_fr75_ph4_samples7_amended_u95_phylo_w12.plainIDs.txt)

**Comment by TaKohl** [comment]
Hello ryobon-dev, it's great to hear that you like the pipeline. Sadly, the functionality to filter for variants specific for a group of strains or single strains is not included in the current version of MTBseq. We can hopefully add that in the next one.

For now, if you have identified SNPs in a multi-fasta file, you can find those in the respective list file with the same name as the multi-fasta file you used as input. Basically, you can take the position of the SNP in the fasta file and look for that row in the list, if you adjust for start at 0/1 and header line accordingly.

Hope that helps, Thomas

**Comment by cutpatel** [comment]
[snp-sites.txt](https://github.com/ngs-fzb/MTBseq_source/files/7677631/snp-sites.txt)

You found the attached 6 positions where for each position 1 strain has a SNP compared to the others.  And you cannot find this position in the TBamend output.

Your result.xlsx is not matching the fasta alignment. In the fasta aligment there are about 1150 positions and in your excel file are only 114. Are you sure this is the correct file and you did not filter already?

**Comment by ryobon-dev** [comment]
Thanks for your quick response.

As you pointed out, it was a wrong file. I am sending a correct one.

Anyway, this issue is resolved. Thank you for your help.


[tab_list.xlsx](https://github.com/ngs-fzb/MTBseq_source/files/7681467/tab_list.xlsx)
