### ISSUE TITLE
File for the repetitive regions of the exchanged reference genome for TBamend

### ISSUE THREAD

**Issue by ryobon-dev** [ngs-fzb/MTBseq_source#72]
Hello, 
With your response to my previous question, I understood the whole process of MTBseq and am really satisfied with the performance.

As the next step, I would like to exchange the reference genome for my use. It is the genome of M. tuberculosis but not H37Rv strain.I have already identified the repetitive regions of the customized reference that can be used to filter the positions at the TBamend step. However, I could not find the original file for the H37Rv in the directory of MTBseq.

Could you please let me know in which directory of MTBseq I can find the original file for repetitive regions that I should replace for my reference genome ? 

I found the FASTA formatted genome sequence in the directory /MTBseq_source/var/ref/ but need your help to find the file for repetitive region.

Thank you very much for your help in advance.

**Comment by cutpatel** [comment]
You can find that in /var/cat/

**Comment by ryobon-dev** [comment]
Thanks,

**Comment by ryobon-dev** [comment]
I checked /var/cat/ and found the file "MTB_Gene_Categories.txt". This is the only file in  /var/cat/.

It is my understanding that you identify repetitive regions as a gene and exclude whole sequence of the gene. For example, "Rv2123	repetitive" in the  MTB_Gene_Categories.txt is excluded for SNP detection at TBamend step.

Am I correct ?

**Comment by TaKohl** [comment]
Yes, that is exactly what is done. We realize that this is not perfect, but together with the other filtering steps employed for filtering for phylogenetically informative variants, this gives excellent results in our experience. More specifically, we could confirm all SNPs discerning an outbreak cluster after these filtering steps (Roetzer et al, 2013). For your interest, the categories in the file are taken from Comas et al., 2010.
