### ISSUE TITLE
gatk3 issue

### ISSUE THREAD

**Issue by JFsanchezherrero** [ngs-fzb/MTBseq_source#74]
Hi there,

I have recently installed MTBseq and I have had an issue regarding `gatk` software.

I installed following these instructions:
```
conda install -c bioconda mtbseq
```

I run `MTBseq --check` and it mentioned `gatk3` was not in the path. Ok, that was expected. So I followed instructions and did:

```
## download gatk
wget https://storage.googleapis.com/gatk-software/package-archive/gatk/GenomeAnalysisTK-3.8-0-ge9d806836.tar.bz2

## untar folder
tar -xf GenomeAnalysisTK-3.8-0-ge9d806836.tar.bz2

## register gatk
...
```
In the registration step, in your `README` files it says to use `gatk3-register`, but I had not `gatk3-register` available in my fresh installed conda environment. I got a `gatk-register` instead (note the missing 3).

So I proceed using:
```
## register gatk
gatk-register GenomeAnalysisTK-3.8-0-ge9d806836/GenomeAnalysisTK.jar 
```

I run again `MTBseq --check` and it mentioned again `gatk3` was not in the path. I check the installation path and Gatk jar file was working fine.

I modified my `MTBseq` perl script code to take into account `gatk3` was now `gatk`. I basically modified lines 135 and 144 in the original script. And it succesfully identified gatk in the path.

https://github.com/ngs-fzb/MTBseq_source/blob/cca5baf743e6bc5e99e60678febffeba8b5e00d3/MTBseq#L135-L144

I am not sure why is it but I guess you should take into account for new users that fresh installed from conda.

I am still running my first example dataset, no issues so far and looks like gatk is found in the path now.

I will let you know if I have any additional issues regarding this modification of the original code.

Best regards,
Jose F.

**Comment by cutpatel** [comment]
The way GATK is handled is really not convinient. It also changed back and forth and was not stable among users, at least what we received as feedback from MTbseq users.
We had it as "gatk" and "gatk-register", but often got the issue that people only had "gatk3" and "gatk3-register" so it was changed.
Now we have the same problem the other way arround. 
For your solution you would also need to change line 115, at least.

The easier solution is to rename the "gatk" in the /bin folder of the environment to "gatk3". This is only a symlink of conda to the gatk starting script. You could also copy it and then rename it, if you need "gatk" in the same environment.

**Comment by JFsanchezherrero** [comment]
Yeah, I forgot to mention that line too. It was already changed and gatk is running rigth now in the TBrefine step.

Ok, great! I tried to found if it was reported before but I did not find any issue related to it.

Sorry if it was duplicated or already taken into account.
Regards,
