### ISSUE TITLE
Can I add additional SNP bar coding for phylogenetic classification ?

### ISSUE THREAD

**Issue by ryobon-dev** [ngs-fzb/MTBseq_source#75]
Coll lineages have been further classified into numbers of sub-lineages. I would like to add some SNP coding so that I can get more resolution for lineage determination.

Can I do this by adding more SNP information to MTB_Resistance_Mediating file ?

**Comment by aspitaleri** [comment]
Hi - I think that the phylo SNPs are hard coded in TBtools.pm. We had a discussion on the same topics with @TaKohl and so far the best solution I found it is to use the Table2 of the https://www.frontiersin.org/articles/10.3389/fmicb.2022.832054/full in a bash script. At the end it is just for 
1.2.1 -> 1.2.1.1 or 1.2.1.2

1.2.2 ->  1.2.2.1 or 1.2.2.2

**Comment by ryobon-dev** [comment]
Thanks,
Recent paper proposed that lineage 2 can be further subdivided. It is really helpful for the global epidemiological study. I have attached the paper and proposed barcoding SNPs.

Could you please consider to incorporate these SNPs in the MTBseq ? Is there anyway to customize MTBseq for this purpose ?

[revised SNP barcoding for L2.pdf](https://github.com/ngs-fzb/MTBseq_source/files/8340102/revised.SNP.barcoding.for.L2.pdf)
[L2_Bar_coding.xlsx](https://github.com/ngs-fzb/MTBseq_source/files/8340159/L2_Bar_coding.xlsx)

**Comment by cutpatel** [comment]
@aspitaleri Please note that also 1.1.1 and 1.1.1.1 slightly changed in our scheme and some strains before classified as 1.1.1 are now 1.1.1.1. as we split on a different branch.

@ryobon-dev As you can see there are several competing nomenclatures out there, there is also the nomencature of napier et al. 2020, and we are not sure how integrate them in the best way right now.
We are working on a solution that a user can just give a list of SNPs with a lineage annotation and will get the classification based on this. If you want to have the output in the Classification directory for the moment your only option is to code them into the TBtools.pm file, starting at line 1048.
https://github.com/ngs-fzb/MTBseq_source/blob/cca5baf743e6bc5e99e60678febffeba8b5e00d3/lib/TBtools.pm#L1048

As you would like to have a refined Beijing classification you could use the code blocks for $phylo_positions_beijing to replace our refined beijing classifcation positions with the positions from the paper.
Next you update the block starting at line 2653 and change the signature SNPs and annotation there.
https://github.com/ngs-fzb/MTBseq_source/blob/cca5baf743e6bc5e99e60678febffeba8b5e00d3/lib/TBtools.pm#L2653

But as you already mentioned you can also add your positions as "phylo" to the MTB_Resistance_Mediating.txt. Starting at line 375:
https://github.com/ngs-fzb/MTBseq_source/blob/cca5baf743e6bc5e99e60678febffeba8b5e00d3/var/res/MTB_Resistance_Mediating.txt#L375

This will populate the PhyloSNP column in the called variant files, which you can parse or manually check to get the lineage classification.

Cheers

**Comment by ryobon-dev** [comment]
Hi,
I am trying to find TBtools.pm in the lib folder. However, I could not find it. The folder where I am seeing is in below. Is this the wrong place ? 
(base) kansensho@DESKTOP-QBEDU0F:~/miniconda3/envs/mtbseq/lib$

**Comment by ryobon-dev** [comment]
I could find it. I am now trying to rewrite TBtools.pm.
I will get back to you if I have any problem on this.
