### ISSUE TITLE
Error failed 256 in .bamlog

### ISSUE THREAD

**Issue by RichardUABC** [ngs-fzb/MTBseq_source#78]
Hi,I have this error "failed 256", but muy ouputs  are like this:

[2022-06-02 01:08:00] bwa mem -t 4 -R '@rg\tID:ERR2512461_S12\tSM:ERR2512461\tPL:Illumina\tLB:S12' /opt/conda/share/mtbseq-1.0.4-2/var/ref/M._tuberculosis_H37Rv_2015-11-13.fasta /home/ubuntudocker/MTB-AMR-CNN_MTBseq/ERR2512461_S12_R1.fastq.gz /home/ubuntudocker/MTB-AMR-CNN_MTBseq/ERR2512461_S12_R2.fastq.gz > /home/ubuntudocker/MTB-AMR-CNN_MTBseq/Bam/ERR2512461_S12.sam 2>> /home/ubuntudocker/MTB-AMR-CNN_MTBseq/Bam/ERR2512461_S12.bamlog
bwa mem -t 4 -R '@rg\tID:ERR2512461_S12\tSM:ERR2512461\tPL:Illumina\tLB:S12' /opt/conda/share/mtbseq-1.0.4-2/var/ref/M._tuberculosis_H37Rv_2015-11-13.fasta /home/ubuntudocker/MTB-AMR-CNN_MTBseq/ERR2512461_S12_R1.fastq.gz /home/ubuntudocker/MTB-AMR-CNN_MTBseq/ERR2512461_S12_R2.fastq.gz > /home/ubuntudocker/MTB-AMR-CNN_MTBseq/Bam/ERR2512461_S12.sam 2>> /home/ubuntudocker/MTB-AMR-CNN_MTBseq/Bam/ERR2512461_S12.bamlog failed: 256

in the bamlog:

[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 264902 sequences (40000202 bp)...
[gzread] fd:4: too many length or distance symbols

or

[M::bwa_idx_load_from_disk] read 0 ALT contigs
[W::bseq_read] the 2nd file has fewer sequences.
[M::process] read 4 sequences (9074220 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[mem_sam_pe] paired reads have different names: "†��ù„„€€€……•š™›…”š—šŸ™š›š��ž›˜˜šŸŸž‰œœœ™ŸšœœŸžœ��œœ™˜š‰šŸ™š›”˜šž’‘Až’““’•�Š–žš€”v’I›•›�‘š™”’™šŠ˜�Ÿ�”ššššŸ˜™š–�™ž™’3˜œ”�‘œ�šž–ž›šžŸ�—Š�žž™š‹y”š›”•„™š—…›”6š–—••š••“””•–Ž•€�––„–†{„;–‡�•’•Š•––i‚•–…2–†Š…g3Œ5��•—�–;•—•”•…dyƒ5…0•––1j‘ej0fh–4q8f:f;f†j9;", "‚�<�BB€š•‚š—•—@‚š”–’�ƒ””:;�•D›‚x‘šŠŠ�‘Š™�›•“˜‹’{’šš•“–�’�š—8z��“�y“‘œ–‡žšz™…;’™™…Ÿ�Ÿž”š˜‰š”•–ˆw‡”ž�ž›–˜�žŸ™˜š�šš‰š“y‰šf7š�’g7Šxš™Š7€1–‡‡‰”™š”h?–˜}Š‚avi0z…0v|†•—„x•…�}1’0t0ha11`ba”…}}…~p|~29•ƒbb;3‡9„3…—–•31hzd9;|ba19j1}231a3a029293xi€}8a2b1"

or

[M::bwa_idx_load_from_disk] read 0 ALT contigs
[W::bseq_read] the 2nd file has fewer sequences.
[M::process] read 12 sequences (75596 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[mem_sam_pe] paired reads have different names: "ERR2512437.1", "rkÔQ�!&eW…Þ��Žn“�ý[™…“¨»”³ËÉ[Ñ{h‹�Š/NãÉY-FÅmPóà�G­�%¬^‡�4¬¬0Ä�H_ôqRB ÊR<á*"

[mem_sam_pe] paired reads have different names: "ERR2512437.4", "ªè‡‚ô,�£�aEêµñ{oŸ^†Eeªæ�­Žz�.À¤³Ù‹S×…an��š³�b~fÕÙM!�§�œ�Ÿ.Œ�‘ì�þ3žüÃo†�§ýÁª¦‰®šý¼,èó��€*2²š"

I tried with the mamba solution and there is no difference. These sequences are downloaded from GenBank. what do you think is the problem?

**Comment by cutpatel** [comment]
Are these files working for you in any other tool?
It seems that it already breaks at the first step of mapping with bwa-mem and it looks like the fastq files do not seem to have the right format or are compromised.

All the special signs may be the problem or if BWA actually handles them, then the order of reads in the files is not the same for the pairs and they need to be reorderd.
