### ISSUE TITLE
gatk does not recognize '--analysis_type'

### ISSUE THREAD

**Issue by Mor-Rubinsteinn** [ngs-fzb/MTBseq_source#79]
I have MTBseq 1.0.3 installed on my linux machine via bioconda. 
I have gatk-4.2.6.1 installed and the command gatk3 points to it. This version of gatk seems to not recognize the --analysis_type option. 
Therefore MTBseq --step TBrefine stops in the middle. 
How do I solve this?
Best Regards,
Mor Rubinstein

**Comment by cutpatel** [comment]
Hi, you need GATK 3.8 (exactly version 3.8!). Version 4 is not working as it does not support certain features anymore.

See the instructions to install it on the front page:

After installation of MTBseq to fully install the GATK, you must download a licensed copy of the GenomeAnalysisTK 3.8 from the Broad Institute (https://console.cloud.google.com/storage/browser/gatk-software/package-archive/gatk). For direct download from the commandline: wget https://storage.googleapis.com/gatk-software/package-archive/gatk/GenomeAnalysisTK-3.8-0-ge9d806836.tar.bz2
