### ISSUE TITLE
Pause and continue

### ISSUE THREAD

**Issue by jloubser** [ngs-fzb/MTBseq_source#81]
Is it possible to pause mid process and then continue? I executed the pipeline with --step TBfull
I want to increase the number of threads to be used...

**Comment by cutpatel** [comment]
Sry for the late reply. You can terminate the pipeline at any step. It is recommended to clean up the output files on which MTBseq was working at time of termination. Afterwards you can start MTBseq again at the specific step with the --step XXX and --continue command to execute the piepline till the end.
