### ISSUE TITLE
Bam issue

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#82]
Hi,

Can someone help me with this? I have old HiSeq files that where in shred 64 formate. I converted to phred33 and went to run MTBseq and it failed with the following error;

bwa mem -t 8 -R '@RG\tID:06IE03_L001_phred33\tSM:06IE03\tPL:Illumina\tLB:L001' /Users/peterflanagan/miniconda3/envs/mtbseq/share/mtbseq-1.0.4-2/var/ref/M._tuberculosis_H37Rv_2015-11-13.fasta  /Volumes/IMRL/Peter_F/Missing_MTBseq_ER/MTBseq/06IE03_L001_phred33_R1.fastq.gz /Volumes/IMRL/Peter_F/Missing_MTBseq_ER/MTBseq/06IE03_L001_phred33_R2.fastq.gz > /Volumes/IMRL/Peter_F/Missing_MTBseq_ER/MTBseq/Bam/06IE03_L001_phred33.sam 2>> /Volumes/IMRL/Peter_F/Missing_MTBseq_ER/MTBseq/Bam/06IE03_L001_phred33.bamlog failed: 256

I looked at the log file and it says this;

[M::bwa_idx_load_from_disk] read 0 ALT contigs
[W::bseq_read] the 2nd file has fewer sequences.
[M::process] read 20 sequences (3020 bp)...
[W::bseq_read] the 2nd file has fewer sequences.
[M::process] read 20 sequences (3020 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (2, 2, 6, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[mem_sam_pe] [mem_sam_pe] paired reads have different names: "HISEQ2500-10:161:HF3TKADXX:2:1114:7144:12013", "HISEQ2500-10:161:HF3TKADXX:1:1213:9256:58517"
[mem_sam_pe] paired reads have different names: "HISEQ2500-10:161:HF3TKADXX:2:1114:7144:12013", "HISEQ2500-10:161:HF3TKADXX:1:1213:9256:58517"

[mem_sam_pe] paired reads have different names: "HISEQ2500-10:161:HF3TKADXX:2:2216:9421:44324", "HISEQ2500-10:161:HF3TKADXX:1:1206:16354:21346"

But I don't understand how it has different names? I should add, these where originally bam files that our lab received from an external lab that did the segueing before I started working here. It was two bam files per sample that I converted to fastq, converted from phred64 to phred33 and then gzip'd the files to run MTBseq.

Any help would be great!

**Comment by cutpatel** [comment]
I hope you already found a solution to this. It looks like that your fastq files are not in order. Read 1 in file 1 must be the mate of read 1 in file 2. 
Maybe see https://github.com/lh3/bwa/issues/228.
