### ISSUE TITLE
TBjoin filename outputs adds number at end

### ISSUE THREAD

**Issue by KatG3** [ngs-fzb/MTBseq_source#83]
Running **TBjoin** outputs files in the Joint folder that adds the number of sequences analyzed at the end of the filename. In this case I was just testing 3 sequences (e,g, tester_joint_cf4_cr4_fr75_ph4_samples**3**.tab) . This creates an issue with **TBamend** which is looking for a filename without this number and gives an error as a result: 

ERROR:
No joint variant file tester_joint_cf4_cr4_fr75_ph4_samples.tab to amend!

If I manually change the filename to remove the number it will work. 

Am I doing something incorrectly or does this require a fix in the code?

**Comment by cutpatel** [comment]
Hi, would be good to have your command and at best the complete logfile. Do you execute TBjoin and Tbamend in 2 different commands?

The sample number is calculated from the --samples xxx.txt file you need to use in that step.
"--samples This OPTION requires a user supplied file specifying a set of datasets (e.g. samples.txt) as VALUE. The file must be a two-column, tab-separated file. Column 1 has to be your [SampleID]. Column 2 has to be your [LibID]."
You also need to give always the correct --project. In your case "tester".
