### ISSUE TITLE
MTBseq Update?

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#84]
Hi, 

this is more a question than an issue. I am just wondering will there be an update of MTBseq anytime soon with the revised WHO mutation catalogue.

Cheers,

P

**Comment by cutpatel** [comment]
Hi,
actually yes! We are running some last tests and it will be available hopefully in the next days then!

**Comment by peflanag** [comment]
Awesome, cheers!

**Comment by ryobon-dev** [comment]
It is great to hear that MTBseq has WHO mutation catalogue.
Have you already updated the version of MTBseq ?

**Comment by cutpatel** [comment]
Sry it took a bit longer, but the updated database is now online and included in the newest release v1.1.0.

**Comment by peflanag** [comment]
Thanks that's great. I'm trying to install into a new condo env to validated it in our laboratory but using conda install -c bioconda mtbseq doesn't seem to work. It's been hanging now for 4 hours. 

Any ideas? I tried mamba install -c bioconda mtbseq but that just installed v1.04

**Comment by cutpatel** [comment]
I think it will take some time until conda also updates.

To get the new predictions right now you can just copy this file:
https://github.com/ngs-fzb/MTBseq_source/blob/master/var/res/MTB_Resistance_Mediating.txt
And then exchange it manually in your conda installation in the /var/res/ directory.

**Comment by peflanag** [comment]
Cheers!

**Comment by peflanag** [comment]
I also meant to ask, will the update have the capabilities for --thread to increase the speed??

Cheers!
