### ISSUE TITLE
No data in the column of ResistanceSNP, PhyloSNP, and InterestingRegion of variants called list.

### ISSUE THREAD

**Issue by ryobon-dev** [ngs-fzb/MTBseq_source#86]
Hi,

I run MTBseq --step TBfull and got full results. However, I noticed that there were  no data in the column of ResistanceSNP, PhyloSNP, and InterestingRegion of variants called list. I have attached the file and log. Could you please let me know how to resolve this issue ?

Thanks,

[JPN-R2013-0096_S23_L001.gatk_position_variants_cf4_cr4_fr75_ph4_outmode000.txt](https://github.com/ngs-fzb/MTBseq_source/files/11207783/JPN-R2013-0096_S23_L001.gatk_position_variants_cf4_cr4_fr75_ph4_outmode000.txt)
[MTBseq_2023-04-12_kansensho.log](https://github.com/ngs-fzb/MTBseq_source/files/11207785/MTBseq_2023-04-12_kansensho.log)

**Comment by cutpatel** [comment]
Hi and sorry for the very late reply,

Could you solve the problem?
I just tested the current github MTBseq version with the WHO updated resistance database and the columns are populated. 
The anaylzed data were from an amplicon approach, therefore only few SNPs are lsited in the variant file.

[SMN-957-B84_lib51315_nextseq_nx0223_151bp.gatk_position_variants_cf4_cr4_fr75_ph4_outmode000.txt](https://github.com/ngs-fzb/MTBseq_source/files/12213190/SMN-957-B84_lib51315_nextseq_nx0223_151bp.gatk_position_variants_cf4_cr4_fr75_ph4_outmode000.txt)
[MTBseq_2023-07-31_cutpatel.log](https://github.com/ngs-fzb/MTBseq_source/files/12213192/MTBseq_2023-07-31_cutpatel.log)
