### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by danaauganova** [ngs-fzb/MTBseq_source#87]
Hi

I was trying to run my files on MTBseq but was getting this issue. How I can solve it? 

ERROR MESSAGE: An error occurred because you did not provide enough memory to run this program. You can use the -xmx argument (before the -jar argument) to adjust the maximum heap size provided to Java. Note that this is a JVM argument, not a GATK argument. 

How I can allow mtbseq to utilize the memory? Probably any commands?

**Comment by cutpatel** [comment]
This is an indicator that the computer you were using did not have enough memory. By default all the memory availbale would be used and there is no need to have this additional commands. The recommendation would be to use a computer with more RAM and/or to observe the memory usage during the run to see if this is the limitation.

There is also no option to give this extra command to MTBseq directly. It would be neccessary to modify the scripts themself with this extra command.

**Comment by danaauganova** [comment]
Thanks!
