### ISSUE TITLE
Option doesn't work --snp_vars 

### ISSUE THREAD

**Issue by ntmscope** [ngs-fzb/MTBseq_source#88]
After running all steps of the MTBseq pipeline I would like to run a large joint analysis (841) with the --snp_vars option. However MTBseq tells me that there are no input files, although there are:

"No files to create joint variant tables! Check content of ~/mtbseq/Position_Tables and /datadisk1~/mtbseq/Called!"

Is there any solution for this?

**Comment by cutpatel** [comment]
Please provide some more details like the general run log and/or specific step log file and your used samples file. We would need to see what files MTBseq expects and what you actually have.

At best you could also provide an example of 2 files which cannot be analyzed.
Is the error the same if you only try to join 2?

**Comment by cutpatel** [comment]
I just ran a small test and all is working fine.
Did you also use the --snp_vars command in the command to start the joining?
Should look like this, if this was the only other option you used:

MTBseq --step TBjoin --snp_vars --sample samples.txt --project TEST -threads 16 --continue

**Comment by cutpatel** [comment]
We actually have changed this behaviour in the latest version. You can now use the --snp_vars option in the TBjoin step also if variant files without theses option were created before. The filter is now applied again in the TBjoin step.
