### ISSUE TITLE
installing v1.1.0

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#89]
Hi, I am trying to install on my MacBook Air M2 using iTerm running Rosetta. I have created a Conda env and when I use Conda to install it just hangs. It's been hating for nearly 24hrs now as you can see from the image below. Is there an issue with the Conda install method?

Cheers!

<img width="716" alt="Screenshot 2023-08-18 at 06 52 11" src="https://github.com/ngs-fzb/MTBseq_source/assets/32863969/fe675391-fefb-4510-a163-79096cd3bb2c">

**Comment by cutpatel** [comment]
Hi, this is usually not a problem of the package itself but of conda and can have multiple reasons. You could first try to update your conda and delete the environment and create it new. Have you setup your channels as recommended by bioconda? You could also try to change channel priority settings: `conda config --set channel_priority flexible` or `conda config --set channel_priority false`. 
You could also try mamba: https://github.com/mamba-org/mamba. I once had success with their not recommended option of installing mamba in the conda base env.
 I found here many other suggestions to try, maybe the libmamba is a good option: https://bobbyhadz.com/blog/solving-environment-failed-with-initial-frozen-solve-retrying#try-to-set-the-solver-to-libmamba

**Comment by peflanag** [comment]
Cheers @cutpatel, I will try these and see!

**Comment by peflanag** [comment]
Just to tag on, the --solver=libmamba worked for anyone else that might be having an issue!

**Comment by cutpatel** [comment]
Great and thanks for sharing your solution!
