### ISSUE TITLE
Bam issue 256

### ISSUE THREAD

**Issue by peflanag** [ngs-fzb/MTBseq_source#90]
Hey, I was using my own isolate as a reference strain and when I run the program it says no file or directory found even though the fasta file is there. Just wondering is there a bug or something? 

The error in the bam file is 

[bwa_idx_build] fail to open file '/Users/drflanman/miniconda3/envs/mtbseq/share/mtbseq-1.0.4-2/var/ref//Users/drflanman/miniconda3/envs/mtbseq/share/mtbseq-1.0.4-2/var/ref/22S3269.fasta' : No such file or directory

for some reason its putting two // after the ref with the path again even though that's not what I typed. I typed,

mtbseq --step TBfull --ref /Users/drflanman/miniconda3/envs/mtbseq/share/mtbseq-1.0.4-2/var/ref/22S3269 --distance 5 --threads 8

Cheers!

**Comment by cutpatel** [comment]
Hi, please have a look at the manual and the paragraph "EXCHANGING THE REFERENCE GENOME". You put your referece file in the var/ref directory and then just need to specify the reference with -ref 22S3269 in your case.

**Comment by peflanag** [comment]
hey @cutpatel my bad! I clearly was having a brain fart! Cheers!
