### ISSUE TITLE
draft genome as reference

### ISSUE THREAD

**Issue by moks-micro** [ngs-fzb/MTBseq_source#92]
Hi, 

Just wondering can draft genomes be used as a reference when running MTBseq ? I am trying to map M. gordonae sequences to the reference genome but there is no complete genome available for Mycobacterium gordonae DSM 44160. The draft genome consists of 260 contigs and when I use it as the reference in MTBseq, the % total bases is only ~3%. 

Thanks in advance!

**Comment by cutpatel** [comment]
You would need to join the contigs into one continious fasta sequence. Use Ns as seperator between sequences and the number of Ns should be greater than the read lenght used.
