### ISSUE TITLE
Problem in the detection of amikacin resistances

### ISSUE THREAD

**Issue by amolares** [ngs-fzb/MTBseq_source#93]
Hi all!

I analysed some samples that contain a mutation related with amikacin resitance, checked by other laboratoy techniques, but when I obtain amended results file, this mutation (genomic coordinate 1473329) only apear associated with streptomycin resistance.
After observing the github folder https://github.com/ngs-fzb/MTBseq_source/tree/master/var/res, I was checking the log obtained in the analysis with MTBseq to a better understanding of the steps how it executes them and I drew some observations:

- The file /master/var/res/MTB_Resistance_Mediating.txt does contain annotations regarding amikacin resistance mutations, but the other file master/var/res/MTB_Extended_Resistance_Mediating.txt does not.
- During variant calling, the file MTB_Resistance_Mediating.txt is consulted and that is why amikacin resistance does appear noted in the vcf files.
- When applying the TBJoin tool, the columns with the antibiotic resistance annotations of the vcf files are deleted, when creating the corresponding tab file.
- When applying the TBAmend tool on this last tab, it happens that

 INFO [2023-09-18 21:19:32] Start parsing /home/user/anaconda3/envs/mtbseq110/share/mtbseq-1.1.0-0/var/res/MTB_Resistance_Mediating.txt and /home/user/anaconda3 /envs/mtbseq110/share/mtbseq-1.1.0-0/var/res/MTB_Extended_Resistance_Mediating.txt..
 INFO [2023-09-18 21:19:32] Finished parsing /home/user/anaconda3/envs/mtbseq110/share/mtbseq-1.1.0-0/var/res/MTB_Resistance_Mediating.txt and /home/user/anaconda3 /envs/mtbseq110/share/mtbseq-1.1.0-0/var/res/MTB_Extended_Resistance_Mediating.txt!
 INFO [2023-09-18 21:19:32] Start creating TEST_joint_cf4_cr4_fr75_ph4_samples5_amended_u95_phylo.tab with window length 12...
 INFO [2023-09-18 21:19:32] Finished creating TEST_joint_cf4_cr4_fr75_ph4_samples5_amended_u95_phylo.tab with window length 12!
 INFO [2023-09-18 21:19:32] Finished amending joint variant table!

The 2 files, MTB_Resistance_Mediating.txt and MTB_Extended_Resistance_Mediating.txt, are consulted, but in the file TEST_joint_cf4_cr4_fr75_ph4_samples5_amended.tab created in this step, the amikacin annotations existing in MTB_Resistance_Mediating.txt no longer appear, but only the corresponding to MTB_Extended_Resistance_Mediating.txt file, which in the same region indicates resistance to streptomycin. I get the feeling that this last file would have overlapped the information from the previous one.

I'm still not clear on how to resolve this. Any idea is welcome.
Thank you very much for the help.

**Comment by cutpatel** [comment]
The use of the joined files for resistance prediction is not recommended. As you experienced yourself a position will not be called resistant if not all compared strains at this position share the mutation that infers resistance. Actually, the column is a bit useless there, but is kept for compatibility. For resistance calls please only refer to the variant files.
