### ISSUE TITLE
Annotation format and column meaning

### ISSUE THREAD

**Issue by SchwarzMarek** [ngs-fzb/MTBseq_source#94]
Hello, thanks for the pipeline
I' want to use different reference and needed to convert annotations as suggested in documentation.
To get the feel about the annotation format, I've looked at the `M.abscessus` annotations; I' not sure what does the following columns mean and if/how this information is used in the pipeline and what are acceptable values:

What I've seen in the file:
```
status_region             [status 3]
status_function          [annotated]
region_number                    [5]
function_number                  [6]
```

Also, since genome can have multiple sequences (chromosomes or incomplete assembly with multiple contigs/scaffolds), how would this be specified in this pipeline, as it appears that no chromosome identification is present in the `*.txt` annotation file.?

**Comment by cutpatel** [comment]
Hi,

the information stored in these columns is not used by MTBseq. Check https://github.com/ngs-fzb/SARSCOV2seq/blob/main/Ref/coronavirus2_wuhan-hu-1_MN908947.3_2020-04-29_genes.txt to see a minimium example. A single genome is accepted as reference. For contigs these need to be joined with Ns inbetween. Number of Ns should be larger than your read length.
