### ISSUE TITLE
Results TBgroups

### ISSUE THREAD

**Issue by acebollada80** [ngs-fzb/MTBseq_source#95]
I'm currently facing an issue with the output files while using MTBseq version 1.0.3 via Docker for analyzing 39 different tuberculosis samples. Here's a breakdown of the steps I've taken:

Ran the command MTBseq --step TBfull --samples samples1202.txt --project Febrero.
Executed various subsequent steps independently:
MTBseq --step TBlist
MTBseq --step TBvariants --snp_vars
MTBseq --step TBstats
MTBseq --step TBstrains
MTBseq --step TBjoin --snp_vars --samples samples1202.txt --project Febrero
MTBseq --step TBamend --samples samples1202.txt --project Febrero
MTBseq --step TBgroups --samples samples1202.txt --project Febrero
The issue arises in the output files of the TBGroups step. While the Strain_Classification file correctly classified the samples, I found discrepancies in the output files. Specifically:

The matrix file Febrero_joint_cf4_cr4_fr75_ph4_samples39_amended_u95_phylo_w12.matrix contains only 0's.
In the file Febrero_joint_cf4_cr4_fr75_ph4_samples39_amended_u95_phylo_w12_d12.groups, all samples are assigned to "group1".
Previously, I encountered similar results when executing MTBseq --step TBvariants. However, I suspected that this might be due to the detection of additional indels and gaps in some samples, leading me to perform the analysis solely with SNPs.

I would greatly appreciate any insights or suggestions on which step might be causing the issue or where to focus to identify the error. Your assistance would be invaluable in resolving this matter.

Thank you all for your time and support.

**Comment by cutpatel** [comment]
Hi,

are the single variant files populated? Are there SNPs detected? Have you checked samples for their overall quality? If you have too many low quality samples in the comparison all possible SNP positions could be filtered. Please also have a look at the FAQ https://github.com/ngs-fzb/MTBseq_source/blob/master/MTBseq%20FAQ.v01.pdf for this, how sample quality impacts the comparison.

**Comment by acebollada80** [comment]
Hi everyone,

Thank you for the comments and suggestions. After reviewing the steps and output files, I identified that the issue was due to some samples having very low sequencing depth. This low depth prevented the detection of SNPs in 95% of the samples, resulting in the incorrect values in the output files.
