### ISSUE TITLE
TBbwa.pm have an issue from Bioconda??

### ISSUE THREAD

**Issue by foamy1881** [ngs-fzb/MTBseq_source#96]
Recently I try to install MTBseq and encounter the following issue: 

Downloading and Extracting Packages:
Preparing transaction: done                                                                                                         
Verifying transaction: -                                                                                                            
SafetyError: The package for mtbseq located at /home/yang/miniconda3/pkgs/mtbseq-1.1.0-hdfd78af_0                                   
appears to be corrupted. The path 'share/mtbseq-1.1.0-0/lib/TBbwa.pm' has an incorrect size.                                                                                                              
reported size: 7901 bytes                                                                                                     
actual size: 7905 bytes

I went ahead to do the smaller sunset analysis and below is my file structure which is correct in accordance to MTBseq requirement but have issue with the TBbwa.pm script. 

(mtbseq) yang@yang-VirtualBox:/media/yang/PhD_NGS1/MTBC_Myanmar_Isolates_Illumina/Original_Raw_Reads_Fastq$ MTBseq --step TBfull

<INFO>	[2024-03-18 03:35:02]	Found perl module: MCE
<INFO>	[2024-03-18 03:35:02]	Found perl module: Statistics::Basic
<INFO>	[2024-03-18 03:35:02]	Found bwa in your PATH!
<INFO>	[2024-03-18 03:35:02]	Found samtools in your PATH!
<INFO>	[2024-03-18 03:35:02]	Found gatk3 in your PATH!
<INFO>	[2024-03-18 03:35:02]	Found picard in your PATH!

MTBseq 1.1.0 - Copyright (C) 2018   Thomas A. Kohl, Robin Koch, Christian Utpatel,
                              Maria Rosaria De Filippo, Viola Schleusener
                              Patrick Beckert, Daniela M. Cirillo, Stefan Niemann

This program comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it under certain conditions.

<INFO>	[2024-03-18 03:35:02]	You are yang.
<INFO>	[2024-03-18 03:35:02]	Your current working directory is: /media/yang/PhD_NGS1/MTBC_Myanmar_Isolates_Illumina/Original_Raw_Reads_Fastq
<INFO>	[2024-03-18 03:35:02]	You requested 1 thread(s) for the pipeline.
<INFO>	[2024-03-18 03:35:02]	Your parameter setting is:
<INFO>	[2024-03-18 03:35:02]	--step		TBfull
<INFO>	[2024-03-18 03:35:02]	--continue	0
<INFO>	[2024-03-18 03:35:02]	--samples	NONE
<INFO>	[2024-03-18 03:35:02]	--project	NONE
<INFO>	[2024-03-18 03:35:02]	--resilist	/home/yang/miniconda3/envs/mtbseq/share/mtbseq-1.1.0-0/var/res/MTB_Resistance_Mediating.txt
<INFO>	[2024-03-18 03:35:02]	--intregions	/home/yang/miniconda3/envs/mtbseq/share/mtbseq-1.1.0-0/var/res/MTB_Extended_Resistance_Mediating.txt
<INFO>	[2024-03-18 03:35:02]	--categories	/home/yang/miniconda3/envs/mtbseq/share/mtbseq-1.1.0-0/var/cat/MTB_Gene_Categories.txt
<INFO>	[2024-03-18 03:35:02]	--basecalib	/home/yang/miniconda3/envs/mtbseq/share/mtbseq-1.1.0-0/var/res/MTB_Base_Calibration_List.vcf
<INFO>	[2024-03-18 03:35:02]	--ref		M._tuberculosis_H37Rv_2015-11-13.fasta
<INFO>	[2024-03-18 03:35:02]	--minbqual	13
<INFO>	[2024-03-18 03:35:02]	--all_vars	0
<INFO>	[2024-03-18 03:35:02]	--snp_vars	0
<INFO>	[2024-03-18 03:35:02]	--lowfreq_vars	0
<INFO>	[2024-03-18 03:35:02]	--mincovf	4
<INFO>	[2024-03-18 03:35:02]	--mincovr	4
<INFO>	[2024-03-18 03:35:02]	--minphred20	4
<INFO>	[2024-03-18 03:35:02]	--minfreq	75
<INFO>	[2024-03-18 03:35:02]	--unambig	95
<INFO>	[2024-03-18 03:35:02]	--window	12
<INFO>	[2024-03-18 03:35:02]	--distance	12
<INFO>	[2024-03-18 03:35:02]	--quiet		0

<INFO>	[2024-03-18 03:35:02]	The following programs will be used, if necessary:
<INFO>	[2024-03-18 03:35:02]	/home/yang/miniconda3/envs/mtbseq/share/mtbseq-1.1.0-0/opt/bwa_0.7.17
<INFO>	[2024-03-18 03:35:02]	/home/yang/miniconda3/envs/mtbseq/share/mtbseq-1.1.0-0/opt/samtools_1.6
<INFO>	[2024-03-18 03:35:02]	/home/yang/miniconda3/envs/mtbseq/share/mtbseq-1.1.0-0/opt/picard_2.17.0
<INFO>	[2024-03-18 03:35:02]	/home/yang/miniconda3/envs/mtbseq/share/mtbseq-1.1.0-0/opt/GenomeAnalysisTK_3.8

<INFO>	[2024-03-18 03:35:02]	The following directories will be used, if necessary:
<INFO>	[2024-03-18 03:35:02]	/media/yang/PhD_NGS1/MTBC_Myanmar_Isolates_Illumina/Original_Raw_Reads_Fastq/Bam
<INFO>	[2024-03-18 03:35:02]	/media/yang/PhD_NGS1/MTBC_Myanmar_Isolates_Illumina/Original_Raw_Reads_Fastq/GATK_Bam
<INFO>	[2024-03-18 03:35:02]	/media/yang/PhD_NGS1/MTBC_Myanmar_Isolates_Illumina/Original_Raw_Reads_Fastq/Mpileup
<INFO>	[2024-03-18 03:35:02]	/media/yang/PhD_NGS1/MTBC_Myanmar_Isolates_Illumina/Original_Raw_Reads_Fastq/Position_Tables
<INFO>	[2024-03-18 03:35:02]	/media/yang/PhD_NGS1/MTBC_Myanmar_Isolates_Illumina/Original_Raw_Reads_Fastq/Called
<INFO>	[2024-03-18 03:35:02]	/media/yang/PhD_NGS1/MTBC_Myanmar_Isolates_Illumina/Original_Raw_Reads_Fastq/Joint
<INFO>	[2024-03-18 03:35:02]	/media/yang/PhD_NGS1/MTBC_Myanmar_Isolates_Illumina/Original_Raw_Reads_Fastq/Amend
<INFO>	[2024-03-18 03:35:02]	/media/yang/PhD_NGS1/MTBC_Myanmar_Isolates_Illumina/Original_Raw_Reads_Fastq/Classification
<INFO>	[2024-03-18 03:35:02]	/media/yang/PhD_NGS1/MTBC_Myanmar_Isolates_Illumina/Original_Raw_Reads_Fastq/Groups
<INFO>	[2024-03-18 03:35:02]	### [TBfull] selected ###

<INFO>	[2024-03-18 03:35:03]	Mapping samples:
<INFO>	[2024-03-18 03:35:03]	M001_R1.fastq.gz
<INFO>	[2024-03-18 03:35:03]	M001_R2.fastq.gz
<INFO>	[2024-03-18 03:35:03]	M002_R1.fastq.gz
<INFO>	[2024-03-18 03:35:03]	M002_R2.fastq.gz
<INFO>	[2024-03-18 03:35:03]	M003_R1.fastq.gz
<INFO>	[2024-03-18 03:35:03]	M003_R2.fastq.gz
<INFO>	[2024-03-18 03:35:03]	M004_R1.fastq.gz
<INFO>	[2024-03-18 03:35:03]	M004_R2.fastq.gz

<INFO>	[2024-03-18 03:35:03]	Start BWA mapping...
syntax error at /home/yang/miniconda3/envs/mtbseq/share/mtbseq-1.1.0-0/lib/TBbwa.pm line 136.  In according to this is the file structure is incorrect for the fastq.gz format? is there something wrong? I failed to pick it up myself and seek additional help from admin.

**Comment by foamy1881** [comment]
additional comment from installation via bioconda route: 
 
Missing right curly or square bracket at /home/yang/miniconda3/envs/mtbseq/share/mtbseq-1.1.0-0/lib/TBbwa.pm line 136, at end of line

syntax error at /home/yang/miniconda3/envs/mtbseq/share/mtbseq-1.1.0-0/lib/TBbwa.pm line 136, at EOF

Compilation failed in require at /home/yang/miniconda3/envs/mtbseq/bin/MTBseq line 10.

BEGIN failed--compilation aborted at /home/yang/miniconda3/envs/mtbseq/bin/MTBseq line 10.

**Comment by cutpatel** [comment]
Hi,

please try to install MTBseq again. I just did a test installation from conda and not got any errors. 
It seems this one file got truncated during your installation.
